:- dynamic pathcost/3.

pathcost('Agartala', 'Ahmedabad', 3305).
pathcost('Ahmedabad', 'Agartala', 3305).
pathcost('Agartala', 'Bangalore', 3824).
pathcost('Bangalore', 'Agartala', 3824).
pathcost('Agartala', 'Bhubaneshwar', 2286).
pathcost('Bhubaneshwar', 'Agartala', 2286).
pathcost('Agartala', 'Bombay', 3593).
pathcost('Bombay', 'Agartala', 3593).
pathcost('Agartala', 'Calcutta', 1863).
pathcost('Calcutta', 'Agartala', 1863).
pathcost('Agartala', 'Chandigarh', 2998).
pathcost('Chandigarh', 'Agartala', 2998).
pathcost('Agartala', 'Cochin', 4304).
pathcost('Cochin', 'Agartala', 4304).
pathcost('Agartala', 'Delhi', 2708).
pathcost('Delhi', 'Agartala', 2708).
pathcost('Agartala', 'Hyderabad', 3330).
pathcost('Hyderabad', 'Agartala', 3330).
pathcost('Agartala', 'Indore', 2891).
pathcost('Indore', 'Agartala', 2891).
pathcost('Agartala', 'Jaipur', 2801).
pathcost('Jaipur', 'Agartala', 2801).
pathcost('Agartala', 'Kanpur', 2281).
pathcost('Kanpur', 'Agartala', 2281).
pathcost('Agartala', 'Lucknow', 2252).
pathcost('Lucknow', 'Agartala', 2252).
pathcost('Agartala', 'Madras', 3493).
pathcost('Madras', 'Agartala', 3493).
pathcost('Agartala', 'Nagpur', 2696).
pathcost('Nagpur', 'Agartala', 2696).
pathcost('Agartala', 'Nasik', 3365).
pathcost('Nasik', 'Agartala', 3365).
pathcost('Agartala', 'Panjim', 3507).
pathcost('Panjim', 'Agartala', 3507).
pathcost('Agartala', 'Patna', 1681).
pathcost('Patna', 'Agartala', 1681).
pathcost('Agartala', 'Pondicherry', 3661).
pathcost('Pondicherry', 'Agartala', 3661).
pathcost('Agartala', 'Pune', 3442).
pathcost('Pune', 'Agartala', 3442).
pathcost('Agra', 'Ahmedabad', 878).
pathcost('Ahmedabad', 'Agra', 878).
pathcost('Agra', 'Bangalore', 1848).
pathcost('Bangalore', 'Agra', 1848).
pathcost('Agra', 'Bhubaneshwar', 1578).
pathcost('Bhubaneshwar', 'Agra', 1578).
pathcost('Agra', 'Bombay', 1202).
pathcost('Bombay', 'Agra', 1202).
pathcost('Agra', 'Calcutta', 1300).
pathcost('Calcutta', 'Agra', 1300).
pathcost('Agra', 'Chandigarh', 448).
pathcost('Chandigarh', 'Agra', 448).
pathcost('Agra', 'Cochin', 2278).
pathcost('Cochin', 'Agra', 2278).
pathcost('Agra', 'Delhi', 200).
pathcost('Delhi', 'Agra', 200).
pathcost('Agra', 'Hyderabad', 1246).
pathcost('Hyderabad', 'Agra', 1246).
pathcost('Agra', 'Indore', 591).
pathcost('Indore', 'Agra', 591).
pathcost('Agra', 'Jaipur', 230).
pathcost('Jaipur', 'Agra', 230).
pathcost('Agra', 'Kanpur', 290).
pathcost('Kanpur', 'Agra', 290).
pathcost('Agra', 'Lucknow', 369).
pathcost('Lucknow', 'Agra', 369).
pathcost('Agra', 'Madras', 2048).
pathcost('Madras', 'Agra', 2048).
pathcost('Agra', 'Nagpur', 770).
pathcost('Nagpur', 'Agra', 770).
pathcost('Agra', 'Nasik', 1005).
pathcost('Nasik', 'Agra', 1005).
pathcost('Agra', 'Panjim', 1715).
pathcost('Panjim', 'Agra', 1715).
pathcost('Agra', 'Patna', 885).
pathcost('Patna', 'Agra', 885).
pathcost('Agra', 'Pondicherry', 2210).
pathcost('Pondicherry', 'Agra', 2210).
pathcost('Agra', 'Pune', 1214).
pathcost('Pune', 'Agra', 1214).
pathcost('Ahmedabad', 'Bangalore', 1490).
pathcost('Bangalore', 'Ahmedabad', 1490).
pathcost('Ahmedabad', 'Bhubaneshwar', 1697).
pathcost('Bhubaneshwar', 'Ahmedabad', 1697).
pathcost('Ahmedabad', 'Bombay', 552).
pathcost('Bombay', 'Ahmedabad', 552).
pathcost('Ahmedabad', 'Calcutta', 2068).
pathcost('Calcutta', 'Ahmedabad', 2068).
pathcost('Ahmedabad', 'Chandigarh', 1157).
pathcost('Chandigarh', 'Ahmedabad', 1157).
pathcost('Ahmedabad', 'Cochin', 1845).
pathcost('Cochin', 'Ahmedabad', 1845).
pathcost('Ahmedabad', 'Delhi', 911).
pathcost('Delhi', 'Ahmedabad', 911).
pathcost('Ahmedabad', 'Hyderabad', 1436).
pathcost('Hyderabad', 'Ahmedabad', 1436).
pathcost('Ahmedabad', 'Indore', 442).
pathcost('Indore', 'Ahmedabad', 442).
pathcost('Ahmedabad', 'Jaipur', 648).
pathcost('Jaipur', 'Ahmedabad', 648).
pathcost('Ahmedabad', 'Kanpur', 1168).
pathcost('Kanpur', 'Ahmedabad', 1168).
pathcost('Ahmedabad', 'Lucknow', 1247).
pathcost('Lucknow', 'Ahmedabad', 1247).
pathcost('Ahmedabad', 'Madras', 1821).
pathcost('Madras', 'Ahmedabad', 1821).
pathcost('Ahmedabad', 'Nagpur', 965).
pathcost('Nagpur', 'Ahmedabad', 965).
pathcost('Ahmedabad', 'Nasik', 504).
pathcost('Nasik', 'Ahmedabad', 504).
pathcost('Ahmedabad', 'Panjim', 1165).
pathcost('Panjim', 'Ahmedabad', 1165).
pathcost('Ahmedabad', 'Patna', 1656).
pathcost('Patna', 'Ahmedabad', 1656).
pathcost('Ahmedabad', 'Pondicherry', 1818).
pathcost('Pondicherry', 'Ahmedabad', 1818).
pathcost('Ahmedabad', 'Pune', 664).
pathcost('Pune', 'Ahmedabad', 664).
pathcost('Allahabad', 'Ahmedabad', 1251).
pathcost('Ahmedabad', 'Allahabad', 1251).
pathcost('Allahabad', 'Bangalore', 1686).
pathcost('Bangalore', 'Allahabad', 1686).
pathcost('Allahabad', 'Bhubaneshwar', 1090).
pathcost('Bhubaneshwar', 'Allahabad', 1090).
pathcost('Allahabad', 'Bombay', 1457).
pathcost('Bombay', 'Allahabad', 1457).
pathcost('Allahabad', 'Calcutta', 817).
pathcost('Calcutta', 'Allahabad', 817).
pathcost('Allahabad', 'Chandigarh', 912).
pathcost('Chandigarh', 'Allahabad', 912).
pathcost('Allahabad', 'Cochin', 2216).
pathcost('Cochin', 'Allahabad', 2216).
pathcost('Allahabad', 'Delhi', 650).
pathcost('Delhi', 'Allahabad', 650).
pathcost('Allahabad', 'Hyderabad', 1084).
pathcost('Hyderabad', 'Allahabad', 1084).
pathcost('Allahabad', 'Indore', 803).
pathcost('Indore', 'Allahabad', 803).
pathcost('Allahabad', 'Jaipur', 713).
pathcost('Jaipur', 'Allahabad', 713).
pathcost('Allahabad', 'Kanpur', 193).
pathcost('Kanpur', 'Allahabad', 193).
pathcost('Allahabad', 'Lucknow', 234).
pathcost('Lucknow', 'Allahabad', 234).
pathcost('Allahabad', 'Madras', 2011).
pathcost('Madras', 'Allahabad', 2011).
pathcost('Allahabad', 'Nagpur', 608).
pathcost('Nagpur', 'Allahabad', 608).
pathcost('Allahabad', 'Nasik', 1155).
pathcost('Nasik', 'Allahabad', 1155).
pathcost('Allahabad', 'Panjim', 1419).
pathcost('Panjim', 'Allahabad', 1419).
pathcost('Allahabad', 'Patna', 402).
pathcost('Patna', 'Allahabad', 402).
pathcost('Allahabad', 'Pondicherry', 1077).
pathcost('Pondicherry', 'Allahabad', 1077).
pathcost('Allahabad', 'Pune', 1364).
pathcost('Pune', 'Allahabad', 1364).
pathcost('Amritsar', 'Ahmedabad', 1356).
pathcost('Ahmedabad', 'Amritsar', 1356).
pathcost('Amritsar', 'Bangalore', 2496).
pathcost('Bangalore', 'Amritsar', 2496).
pathcost('Amritsar', 'Bhubaneshwar', 2224).
pathcost('Bhubaneshwar', 'Amritsar', 2224).
pathcost('Amritsar', 'Bombay', 1849).
pathcost('Bombay', 'Amritsar', 1849).
pathcost('Amritsar', 'Calcutta', 1919).
pathcost('Calcutta', 'Amritsar', 1919).
pathcost('Amritsar', 'Chandigarh', 239).
pathcost('Chandigarh', 'Amritsar', 239).
pathcost('Amritsar', 'Cochin', 3163).
pathcost('Cochin', 'Amritsar', 3163).
pathcost('Amritsar', 'Delhi', 445).
pathcost('Delhi', 'Amritsar', 445).
pathcost('Amritsar', 'Hyderabad', 1892).
pathcost('Hyderabad', 'Amritsar', 1892).
pathcost('Amritsar', 'Indore', 1258).
pathcost('Indore', 'Amritsar', 1258).
pathcost('Amritsar', 'Jaipur', 706).
pathcost('Jaipur', 'Amritsar', 706).
pathcost('Amritsar', 'Kanpur', 926).
pathcost('Kanpur', 'Amritsar', 926).
pathcost('Amritsar', 'Lucknow', 939).
pathcost('Lucknow', 'Amritsar', 939).
pathcost('Amritsar', 'Madras', 2688).
pathcost('Madras', 'Amritsar', 2688).
pathcost('Amritsar', 'Nagpur', 1416).
pathcost('Nagpur', 'Amritsar', 1416).
pathcost('Amritsar', 'Nasik', 1665).
pathcost('Nasik', 'Amritsar', 1665).
pathcost('Amritsar', 'Panjim', 2237).
pathcost('Panjim', 'Amritsar', 2237).
pathcost('Amritsar', 'Patna', 1531).
pathcost('Patna', 'Amritsar', 1531).
pathcost('Amritsar', 'Pondicherry', 2856).
pathcost('Pondicherry', 'Amritsar', 2856).
pathcost('Amritsar', 'Pune', 1862).
pathcost('Pune', 'Amritsar', 1862).
pathcost('Asansol', 'Ahmedabad', 1842).
pathcost('Ahmedabad', 'Asansol', 1842).
pathcost('Asansol', 'Bangalore', 2187).
pathcost('Bangalore', 'Asansol', 2187).
pathcost('Asansol', 'Bhubaneshwar', 523).
pathcost('Bhubaneshwar', 'Asansol', 523).
pathcost('Asansol', 'Bombay', 2040).
pathcost('Bombay', 'Asansol', 2040).
pathcost('Asansol', 'Calcutta', 226).
pathcost('Calcutta', 'Asansol', 226).
pathcost('Asansol', 'Chandigarh', 1503).
pathcost('Chandigarh', 'Asansol', 1503).
pathcost('Asansol', 'Cochin', 2544).
pathcost('Cochin', 'Asansol', 2544).
pathcost('Asansol', 'Delhi', 1262).
pathcost('Delhi', 'Asansol', 1262).
pathcost('Asansol', 'Hyderabad', 1693).
pathcost('Hyderabad', 'Asansol', 1693).
pathcost('Asansol', 'Indore', 1394).
pathcost('Indore', 'Asansol', 1394).
pathcost('Asansol', 'Jaipur', 1304).
pathcost('Jaipur', 'Asansol', 1304).
pathcost('Asansol', 'Kanpur', 789).
pathcost('Kanpur', 'Asansol', 789).
pathcost('Asansol', 'Lucknow', 825).
pathcost('Lucknow', 'Asansol', 825).
pathcost('Asansol', 'Madras', 1857).
pathcost('Madras', 'Asansol', 1857).
pathcost('Asansol', 'Nagpur', 1122).
pathcost('Nagpur', 'Asansol', 1122).
pathcost('Asansol', 'Nasik', 1746).
pathcost('Nasik', 'Asansol', 1746).
pathcost('Asansol', 'Panjim', 2300).
pathcost('Panjim', 'Asansol', 2300).
pathcost('Asansol', 'Patna', 395).
pathcost('Patna', 'Asansol', 395).
pathcost('Asansol', 'Pondicherry', 2024).
pathcost('Pondicherry', 'Asansol', 2024).
pathcost('Asansol', 'Pune', 1955).
pathcost('Pune', 'Asansol', 1955).
pathcost('Bangalore', 'Ahmedabad', 1490).
pathcost('Ahmedabad', 'Bangalore', 1490).
pathcost('Bangalore', 'Bhubaneshwar', 1538).
pathcost('Bhubaneshwar', 'Bangalore', 1538).
pathcost('Bangalore', 'Bombay', 1013).
pathcost('Bombay', 'Bangalore', 1013).
pathcost('Bangalore', 'Calcutta', 1961).
pathcost('Calcutta', 'Bangalore', 1961).
pathcost('Bangalore', 'Chandigarh', 2296).
pathcost('Chandigarh', 'Bangalore', 2296).
pathcost('Bangalore', 'Cochin', 512).
pathcost('Cochin', 'Bangalore', 512).
pathcost('Bangalore', 'Delhi', 2049).
pathcost('Delhi', 'Bangalore', 2049).
pathcost('Bangalore', 'Hyderabad', 563).
pathcost('Hyderabad', 'Bangalore', 563).
pathcost('Bangalore', 'Indore', 1601).
pathcost('Indore', 'Bangalore', 1601).
pathcost('Bangalore', 'Jaipur', 2005).
pathcost('Jaipur', 'Bangalore', 2005).
pathcost('Bangalore', 'Kanpur', 1855).
pathcost('Kanpur', 'Bangalore', 1855).
pathcost('Bangalore', 'Lucknow', 1934).
pathcost('Lucknow', 'Bangalore', 1934).
pathcost('Bangalore', 'Madras', 331).
pathcost('Madras', 'Bangalore', 331).
pathcost('Bangalore', 'Nagpur', 1078).
pathcost('Nagpur', 'Bangalore', 1078).
pathcost('Bangalore', 'Nasik', 1035).
pathcost('Nasik', 'Bangalore', 1035).
pathcost('Bangalore', 'Panjim', 440).
pathcost('Panjim', 'Bangalore', 440).
pathcost('Bangalore', 'Patna', 2071).
pathcost('Patna', 'Bangalore', 2071).
pathcost('Bangalore', 'Pondicherry', 328).
pathcost('Pondicherry', 'Bangalore', 328).
pathcost('Bangalore', 'Pune', 826).
pathcost('Pune', 'Bangalore', 826).
pathcost('Baroda', 'Ahmedabad', 119).
pathcost('Ahmedabad', 'Baroda', 119).
pathcost('Baroda', 'Bangalore', 1408).
pathcost('Bangalore', 'Baroda', 1408).
pathcost('Baroda', 'Bhubaneshwar', 1604).
pathcost('Bhubaneshwar', 'Baroda', 1604).
pathcost('Baroda', 'Bombay', 433).
pathcost('Bombay', 'Baroda', 433).
pathcost('Baroda', 'Calcutta', 1937).
pathcost('Calcutta', 'Baroda', 1937).
pathcost('Baroda', 'Chandigarh', 1181).
pathcost('Chandigarh', 'Baroda', 1181).
pathcost('Baroda', 'Cochin', 1763).
pathcost('Cochin', 'Baroda', 1763).
pathcost('Baroda', 'Delhi', 1151).
pathcost('Delhi', 'Baroda', 1151).
pathcost('Baroda', 'Hyderabad', 1127).
pathcost('Hyderabad', 'Baroda', 1127).
pathcost('Baroda', 'Indore', 379).
pathcost('Indore', 'Baroda', 379).
pathcost('Baroda', 'Jaipur', 789).
pathcost('Jaipur', 'Baroda', 789).
pathcost('Baroda', 'Kanpur', 1230).
pathcost('Kanpur', 'Baroda', 1230).
pathcost('Baroda', 'Lucknow', 1311).
pathcost('Lucknow', 'Baroda', 1311).
pathcost('Baroda', 'Madras', 1739).
pathcost('Madras', 'Baroda', 1739).
pathcost('Baroda', 'Nagpur', 774).
pathcost('Nagpur', 'Baroda', 774).
pathcost('Baroda', 'Nasik', 457).
pathcost('Nasik', 'Baroda', 457).
pathcost('Baroda', 'Panjim', 1158).
pathcost('Panjim', 'Baroda', 1158).
pathcost('Baroda', 'Patna', 1582).
pathcost('Patna', 'Baroda', 1582).
pathcost('Baroda', 'Pondicherry', 1735).
pathcost('Pondicherry', 'Baroda', 1735).
pathcost('Baroda', 'Pune', 545).
pathcost('Pune', 'Baroda', 545).
pathcost('Bhopal', 'Ahmedabad', 523).
pathcost('Ahmedabad', 'Bhopal', 523).
pathcost('Bhopal', 'Bangalore', 1148).
pathcost('Bangalore', 'Bhopal', 1148).
pathcost('Bhopal', 'Bhubaneshwar', 1162).
pathcost('Bhubaneshwar', 'Bhopal', 1162).
pathcost('Bhopal', 'Bombay', 778).
pathcost('Bombay', 'Bhopal', 778).
pathcost('Bhopal', 'Calcutta', 1495).
pathcost('Calcutta', 'Bhopal', 1495).
pathcost('Bhopal', 'Chandigarh', 988).
pathcost('Chandigarh', 'Bhopal', 988).
pathcost('Bhopal', 'Cochin', 1995).
pathcost('Cochin', 'Bhopal', 1995).
pathcost('Bhopal', 'Delhi', 742).
pathcost('Delhi', 'Bhopal', 742).
pathcost('Bhopal', 'Hyderabad', 808).
pathcost('Hyderabad', 'Bhopal', 808).
pathcost('Bhopal', 'Indore', 191).
pathcost('Indore', 'Bhopal', 191).
pathcost('Bhopal', 'Jaipur', 596).
pathcost('Jaipur', 'Bhopal', 596).
pathcost('Bhopal', 'Kanpur', 585).
pathcost('Kanpur', 'Bhopal', 585).
pathcost('Bhopal', 'Lucknow', 664).
pathcost('Lucknow', 'Bhopal', 664).
pathcost('Bhopal', 'Madras', 1604).
pathcost('Madras', 'Bhopal', 1604).
pathcost('Bhopal', 'Nagpur', 352).
pathcost('Nagpur', 'Bhopal', 352).
pathcost('Bhopal', 'Nasik', 605).
pathcost('Nasik', 'Bhopal', 605).
pathcost('Bhopal', 'Panjim', 1143).
pathcost('Panjim', 'Bhopal', 1143).
pathcost('Bhopal', 'Patna', 1016).
pathcost('Patna', 'Bhopal', 1016).
pathcost('Bhopal', 'Pondicherry', 1772).
pathcost('Pondicherry', 'Bhopal', 1772).
pathcost('Bhopal', 'Pune', 814).
pathcost('Pune', 'Bhopal', 814).
pathcost('Bhubaneshwar', 'Ahmedabad', 1647).
pathcost('Ahmedabad', 'Bhubaneshwar', 1647).
pathcost('Bhubaneshwar', 'Bangalore', 1538).
pathcost('Bangalore', 'Bhubaneshwar', 1538).
pathcost('Bhubaneshwar', 'Bombay', 1679).
pathcost('Bombay', 'Bhubaneshwar', 1679).
pathcost('Bhubaneshwar', 'Calcutta', 423).
pathcost('Calcutta', 'Bhubaneshwar', 423).
pathcost('Bhubaneshwar', 'Chandigarh', 2026).
pathcost('Chandigarh', 'Bhubaneshwar', 2026).
pathcost('Bhubaneshwar', 'Cochin', 1895).
pathcost('Cochin', 'Bhubaneshwar', 1895).
pathcost('Bhubaneshwar', 'Delhi', 1713).
pathcost('Delhi', 'Bhubaneshwar', 1713).
pathcost('Bhubaneshwar', 'Hyderabad', 1044).
pathcost('Hyderabad', 'Bhubaneshwar', 1044).
pathcost('Bhubaneshwar', 'Indore', 1355).
pathcost('Indore', 'Bhubaneshwar', 1355).
pathcost('Bhubaneshwar', 'Jaipur', 1758).
pathcost('Jaipur', 'Bhubaneshwar', 1758).
pathcost('Bhubaneshwar', 'Kanpur', 1283).
pathcost('Kanpur', 'Bhubaneshwar', 1283).
pathcost('Bhubaneshwar', 'Lucknow', 1254).
pathcost('Lucknow', 'Bhubaneshwar', 1254).
pathcost('Bhubaneshwar', 'Madras', 1207).
pathcost('Madras', 'Bhubaneshwar', 1207).
pathcost('Bhubaneshwar', 'Nagpur', 830).
pathcost('Nagpur', 'Bhubaneshwar', 830).
pathcost('Bhubaneshwar', 'Nasik', 1516).
pathcost('Nasik', 'Bhubaneshwar', 1516).
pathcost('Bhubaneshwar', 'Panjim', 1455).
pathcost('Panjim', 'Bhubaneshwar', 1455).
pathcost('Bhubaneshwar', 'Patna', 862).
pathcost('Patna', 'Bhubaneshwar', 862).
pathcost('Bhubaneshwar', 'Pondicherry', 1375).
pathcost('Pondicherry', 'Bhubaneshwar', 1375).
pathcost('Bhubaneshwar', 'Pune', 1587).
pathcost('Pune', 'Bhubaneshwar', 1587).
pathcost('Bombay', 'Ahmedabad', 552).
pathcost('Ahmedabad', 'Bombay', 552).
pathcost('Bombay', 'Bangalore', 1013).
pathcost('Bangalore', 'Bombay', 1013).
pathcost('Bombay', 'Bhubaneshwar', 1678).
pathcost('Bhubaneshwar', 'Bombay', 1678).
pathcost('Bombay', 'Calcutta', 2012).
pathcost('Calcutta', 'Bombay', 2012).
pathcost('Bombay', 'Chandigarh', 1645).
pathcost('Chandigarh', 'Bombay', 1645).
pathcost('Bombay', 'Cochin', 1368).
pathcost('Cochin', 'Bombay', 1368).
pathcost('Bombay', 'Delhi', 1404).
pathcost('Delhi', 'Bombay', 1404).
pathcost('Bombay', 'Hyderabad', 729).
pathcost('Hyderabad', 'Bombay', 729).
pathcost('Bombay', 'Indore', 589).
pathcost('Indore', 'Bombay', 589).
pathcost('Bombay', 'Jaipur', 1148).
pathcost('Jaipur', 'Bombay', 1148).
pathcost('Bombay', 'Kanpur', 1278).
pathcost('Kanpur', 'Bombay', 1278).
pathcost('Bombay', 'Lucknow', 1366).
pathcost('Lucknow', 'Bombay', 1366).
pathcost('Bombay', 'Madras', 1344).
pathcost('Madras', 'Bombay', 1344).
pathcost('Bombay', 'Nagpur', 849).
pathcost('Nagpur', 'Bombay', 849).
pathcost('Bombay', 'Nasik', 197).
pathcost('Nasik', 'Bombay', 197).
pathcost('Bombay', 'Panjim', 584).
pathcost('Panjim', 'Bombay', 584).
pathcost('Bombay', 'Patna', 1856).
pathcost('Patna', 'Bombay', 1856).
pathcost('Bombay', 'Pondicherry', 1452).
pathcost('Pondicherry', 'Bombay', 1452).
pathcost('Bombay', 'Pune', 184).
pathcost('Pune', 'Bombay', 184).
pathcost('Calcutta', 'Ahmedabad', 2068).
pathcost('Ahmedabad', 'Calcutta', 2068).
pathcost('Calcutta', 'Bangalore', 1461).
pathcost('Bangalore', 'Calcutta', 1461).
pathcost('Calcutta', 'Bhubaneshwar', 423).
pathcost('Bhubaneshwar', 'Calcutta', 423).
pathcost('Calcutta', 'Bombay', 2012).
pathcost('Bombay', 'Calcutta', 2012).
pathcost('Calcutta', 'Chandigarh', 1721).
pathcost('Chandigarh', 'Calcutta', 1721).
pathcost('Calcutta', 'Cochin', 2318).
pathcost('Cochin', 'Calcutta', 2318).
pathcost('Calcutta', 'Delhi', 1474).
pathcost('Delhi', 'Calcutta', 1474).
pathcost('Calcutta', 'Hyderabad', 1467).
pathcost('Hyderabad', 'Calcutta', 1467).
pathcost('Calcutta', 'Indore', 1620).
pathcost('Indore', 'Calcutta', 1620).
pathcost('Calcutta', 'Jaipur', 1530).
pathcost('Jaipur', 'Calcutta', 1530).
pathcost('Calcutta', 'Kanpur', 1010).
pathcost('Kanpur', 'Calcutta', 1010).
pathcost('Calcutta', 'Lucknow', 1089).
pathcost('Lucknow', 'Calcutta', 1089).
pathcost('Calcutta', 'Madras', 1160).
pathcost('Madras', 'Calcutta', 1160).
pathcost('Calcutta', 'Nagpur', 1163).
pathcost('Nagpur', 'Calcutta', 1163).
pathcost('Calcutta', 'Nasik', 1849).
pathcost('Nasik', 'Calcutta', 1849).
pathcost('Calcutta', 'Panjim', 974).
pathcost('Panjim', 'Calcutta', 974).
pathcost('Calcutta', 'Patna', 621).
pathcost('Patna', 'Calcutta', 621).
pathcost('Calcutta', 'Pondicherry', 1798).
pathcost('Pondicherry', 'Calcutta', 1798).
pathcost('Calcutta', 'Pune', 2058).
pathcost('Pune', 'Calcutta', 2058).
pathcost('Calicut', 'Ahmedabad', 1648).
pathcost('Ahmedabad', 'Calicut', 1648).
pathcost('Calicut', 'Bangalore', 520).
pathcost('Bangalore', 'Calicut', 520).
pathcost('Calicut', 'Bhubaneshwar', 1923).
pathcost('Bhubaneshwar', 'Calicut', 1923).
pathcost('Calicut', 'Bombay', 1171).
pathcost('Bombay', 'Calicut', 1171).
pathcost('Calicut', 'Calcutta', 2346).
pathcost('Calcutta', 'Calicut', 2346).
pathcost('Calicut', 'Chandigarh', 2741).
pathcost('Chandigarh', 'Calicut', 2741).
pathcost('Calicut', 'Cochin', 222).
pathcost('Cochin', 'Calicut', 222).
pathcost('Calicut', 'Delhi', 2494).
pathcost('Delhi', 'Calicut', 2494).
pathcost('Calicut', 'Hyderabad', 910).
pathcost('Hyderabad', 'Calicut', 910).
pathcost('Calicut', 'Indore', 1998).
pathcost('Indore', 'Calicut', 1998).
pathcost('Calicut', 'Jaipur', 2523).
pathcost('Jaipur', 'Calicut', 2523).
pathcost('Calicut', 'Kanpur', 2260).
pathcost('Kanpur', 'Calicut', 2260).
pathcost('Calicut', 'Lucknow', 2339).
pathcost('Lucknow', 'Calicut', 2339).
pathcost('Calicut', 'Madras', 715).
pathcost('Madras', 'Calicut', 715).
pathcost('Calicut', 'Nagpur', 1483).
pathcost('Nagpur', 'Calicut', 1483).
pathcost('Calicut', 'Nasik', 1193).
pathcost('Nasik', 'Calicut', 1193).
pathcost('Calicut', 'Panjim', 576).
pathcost('Panjim', 'Calicut', 576).
pathcost('Calicut', 'Patna', 2476).
pathcost('Patna', 'Calicut', 2476).
pathcost('Calicut', 'Pondicherry', 566).
pathcost('Pondicherry', 'Calicut', 566).
pathcost('Calicut', 'Pune', 984).
pathcost('Pune', 'Calicut', 984).
pathcost('Chandigarh', 'Ahmedabad', 1157).
pathcost('Ahmedabad', 'Chandigarh', 1157).
pathcost('Chandigarh', 'Bangalore', 2296).
pathcost('Bangalore', 'Chandigarh', 2296).
pathcost('Chandigarh', 'Bhubaneshwar', 2026).
pathcost('Bhubaneshwar', 'Chandigarh', 2026).
pathcost('Chandigarh', 'Bombay', 1645).
pathcost('Bombay', 'Chandigarh', 1645).
pathcost('Chandigarh', 'Calcutta', 1721).
pathcost('Calcutta', 'Chandigarh', 1721).
pathcost('Chandigarh', 'Cochin', 1965).
pathcost('Cochin', 'Chandigarh', 1965).
pathcost('Chandigarh', 'Delhi', 248).
pathcost('Delhi', 'Chandigarh', 248).
pathcost('Chandigarh', 'Hyderabad', 1693).
pathcost('Hyderabad', 'Chandigarh', 1693).
pathcost('Chandigarh', 'Indore', 1052).
pathcost('Indore', 'Chandigarh', 1052).
pathcost('Chandigarh', 'Jaipur', 507).
pathcost('Jaipur', 'Chandigarh', 507).
pathcost('Chandigarh', 'Kanpur', 661).
pathcost('Kanpur', 'Chandigarh', 661).
pathcost('Chandigarh', 'Lucknow', 740).
pathcost('Lucknow', 'Chandigarh', 740).
pathcost('Chandigarh', 'Madras', 2489).
pathcost('Madras', 'Chandigarh', 2489).
pathcost('Chandigarh', 'Nagpur', 1217).
pathcost('Nagpur', 'Chandigarh', 1217).
pathcost('Chandigarh', 'Nasik', 1466).
pathcost('Nasik', 'Chandigarh', 1466).
pathcost('Chandigarh', 'Panjim', 2028).
pathcost('Panjim', 'Chandigarh', 2028).
pathcost('Chandigarh', 'Patna', 1332).
pathcost('Patna', 'Chandigarh', 1332).
pathcost('Chandigarh', 'Pondicherry', 2657).
pathcost('Pondicherry', 'Chandigarh', 2657).
pathcost('Chandigarh', 'Pune', 1663).
pathcost('Pune', 'Chandigarh', 1663).
pathcost('Cochin', 'Ahmedabad', 1845).
pathcost('Ahmedabad', 'Cochin', 1845).
pathcost('Cochin', 'Bangalore', 512).
pathcost('Bangalore', 'Cochin', 512).
pathcost('Cochin', 'Bhubaneshwar', 1895).
pathcost('Bhubaneshwar', 'Cochin', 1895).
pathcost('Cochin', 'Bombay', 1368).
pathcost('Bombay', 'Cochin', 1368).
pathcost('Cochin', 'Calcutta', 2318).
pathcost('Calcutta', 'Cochin', 2318).
pathcost('Cochin', 'Chandigarh', 1965).
pathcost('Chandigarh', 'Cochin', 1965).
pathcost('Cochin', 'Delhi', 2718).
pathcost('Delhi', 'Cochin', 2718).
pathcost('Cochin', 'Hyderabad', 1090).
pathcost('Hyderabad', 'Cochin', 1090).
pathcost('Cochin', 'Indore', 1804).
pathcost('Indore', 'Cochin', 1804).
pathcost('Cochin', 'Jaipur', 2745).
pathcost('Jaipur', 'Cochin', 2745).
pathcost('Cochin', 'Kanpur', 2385).
pathcost('Kanpur', 'Cochin', 2385).
pathcost('Cochin', 'Lucknow', 2572).
pathcost('Lucknow', 'Cochin', 2572).
pathcost('Cochin', 'Madras', 687).
pathcost('Madras', 'Cochin', 687).
pathcost('Cochin', 'Nagpur', 1608).
pathcost('Nagpur', 'Cochin', 1608).
pathcost('Cochin', 'Nasik', 1390).
pathcost('Nasik', 'Cochin', 1390).
pathcost('Cochin', 'Panjim', 798).
pathcost('Panjim', 'Cochin', 798).
pathcost('Cochin', 'Patna', 2601).
pathcost('Patna', 'Cochin', 2601).
pathcost('Cochin', 'Pondicherry', 530).
pathcost('Pondicherry', 'Cochin', 530).
pathcost('Cochin', 'Pune', 1181).
pathcost('Pune', 'Cochin', 1181).
pathcost('Coimbatore', 'Ahmedabad', 1669).
pathcost('Ahmedabad', 'Coimbatore', 1669).
pathcost('Coimbatore', 'Bangalore', 333).
pathcost('Bangalore', 'Coimbatore', 333).
pathcost('Coimbatore', 'Bhubaneshwar', 1633).
pathcost('Bhubaneshwar', 'Coimbatore', 1633).
pathcost('Coimbatore', 'Bombay', 1192).
pathcost('Bombay', 'Coimbatore', 1192).
pathcost('Coimbatore', 'Calcutta', 2057).
pathcost('Calcutta', 'Coimbatore', 2057).
pathcost('Coimbatore', 'Chandigarh', 2669).
pathcost('Chandigarh', 'Coimbatore', 2669).
pathcost('Coimbatore', 'Cochin', 195).
pathcost('Cochin', 'Coimbatore', 195).
pathcost('Coimbatore', 'Delhi', 2412).
pathcost('Delhi', 'Coimbatore', 2412).
pathcost('Coimbatore', 'Hyderabad', 912).
pathcost('Hyderabad', 'Coimbatore', 912).
pathcost('Coimbatore', 'Indore', 1964).
pathcost('Indore', 'Coimbatore', 1964).
pathcost('Coimbatore', 'Jaipur', 2369).
pathcost('Jaipur', 'Coimbatore', 2369).
pathcost('Coimbatore', 'Kanpur', 2218).
pathcost('Kanpur', 'Coimbatore', 2218).
pathcost('Coimbatore', 'Lucknow', 2297).
pathcost('Lucknow', 'Coimbatore', 2297).
pathcost('Coimbatore', 'Madras', 426).
pathcost('Madras', 'Coimbatore', 426).
pathcost('Coimbatore', 'Nagpur', 1441).
pathcost('Nagpur', 'Coimbatore', 1441).
pathcost('Coimbatore', 'Nasik', 1214).
pathcost('Nasik', 'Coimbatore', 1214).
pathcost('Coimbatore', 'Panjim', 800).
pathcost('Panjim', 'Coimbatore', 800).
pathcost('Coimbatore', 'Patna', 2434).
pathcost('Patna', 'Coimbatore', 2434).
pathcost('Coimbatore', 'Pondicherry', 410).
pathcost('Pondicherry', 'Coimbatore', 410).
pathcost('Coimbatore', 'Pune', 1005).
pathcost('Pune', 'Coimbatore', 1005).
pathcost('Delhi', 'Ahmedabad', 911).
pathcost('Ahmedabad', 'Delhi', 911).
pathcost('Delhi', 'Bangalore', 2049).
pathcost('Bangalore', 'Delhi', 2049).
pathcost('Delhi', 'Bhubaneshwar', 1713).
pathcost('Bhubaneshwar', 'Delhi', 1713).
pathcost('Delhi', 'Bombay', 1404).
pathcost('Bombay', 'Delhi', 1404).
pathcost('Delhi', 'Calcutta', 1474).
pathcost('Calcutta', 'Delhi', 1474).
pathcost('Delhi', 'Chandigarh', 248).
pathcost('Chandigarh', 'Delhi', 248).
pathcost('Delhi', 'Cochin', 2718).
pathcost('Cochin', 'Delhi', 2718).
pathcost('Delhi', 'Hyderabad', 1477).
pathcost('Hyderabad', 'Delhi', 1477).
pathcost('Delhi', 'Indore', 806).
pathcost('Indore', 'Delhi', 806).
pathcost('Delhi', 'Jaipur', 263).
pathcost('Jaipur', 'Delhi', 263).
pathcost('Delhi', 'Kanpur', 481).
pathcost('Kanpur', 'Delhi', 481).
pathcost('Delhi', 'Lucknow', 499).
pathcost('Lucknow', 'Delhi', 499).
pathcost('Delhi', 'Madras', 2243).
pathcost('Madras', 'Delhi', 2243).
pathcost('Delhi', 'Nagpur', 971).
pathcost('Nagpur', 'Delhi', 971).
pathcost('Delhi', 'Nasik', 1220).
pathcost('Nasik', 'Delhi', 1220).
pathcost('Delhi', 'Panjim', 1782).
pathcost('Panjim', 'Delhi', 1782).
pathcost('Delhi', 'Patna', 1086).
pathcost('Patna', 'Delhi', 1086).
pathcost('Delhi', 'Pondicherry', 2411).
pathcost('Pondicherry', 'Delhi', 2411).
pathcost('Delhi', 'Pune', 1417).
pathcost('Pune', 'Delhi', 1417).
pathcost('Gwalior', 'Ahmedabad', 919).
pathcost('Ahmedabad', 'Gwalior', 919).
pathcost('Gwalior', 'Bangalore', 1734).
pathcost('Bangalore', 'Gwalior', 1734).
pathcost('Gwalior', 'Bhubaneshwar', 1486).
pathcost('Bhubaneshwar', 'Gwalior', 1486).
pathcost('Gwalior', 'Bombay', 1085).
pathcost('Bombay', 'Gwalior', 1085).
pathcost('Gwalior', 'Calcutta', 1224).
pathcost('Calcutta', 'Gwalior', 1224).
pathcost('Gwalior', 'Chandigarh', 462).
pathcost('Chandigarh', 'Gwalior', 462).
pathcost('Gwalior', 'Cochin', 1881).
pathcost('Cochin', 'Gwalior', 1881).
pathcost('Gwalior', 'Delhi', 315).
pathcost('Delhi', 'Gwalior', 315).
pathcost('Gwalior', 'Hyderabad', 1132).
pathcost('Hyderabad', 'Gwalior', 1132).
pathcost('Gwalior', 'Indore', 497).
pathcost('Indore', 'Gwalior', 497).
pathcost('Gwalior', 'Jaipur', 351).
pathcost('Jaipur', 'Gwalior', 351).
pathcost('Gwalior', 'Kanpur', 280).
pathcost('Kanpur', 'Gwalior', 280).
pathcost('Gwalior', 'Lucknow', 359).
pathcost('Lucknow', 'Gwalior', 359).
pathcost('Gwalior', 'Madras', 1928).
pathcost('Madras', 'Gwalior', 1928).
pathcost('Gwalior', 'Nagpur', 656).
pathcost('Nagpur', 'Gwalior', 656).
pathcost('Gwalior', 'Nasik', 891).
pathcost('Nasik', 'Gwalior', 891).
pathcost('Gwalior', 'Panjim', 1467).
pathcost('Panjim', 'Gwalior', 1467).
pathcost('Gwalior', 'Patna', 809).
pathcost('Patna', 'Gwalior', 809).
pathcost('Gwalior', 'Pondicherry', 2096).
pathcost('Pondicherry', 'Gwalior', 2096).
pathcost('Gwalior', 'Pune', 1100).
pathcost('Pune', 'Gwalior', 1100).
pathcost('Hubli', 'Ahmedabad', 1101).
pathcost('Ahmedabad', 'Hubli', 1101).
pathcost('Hubli', 'Bangalore', 391).
pathcost('Bangalore', 'Hubli', 391).
pathcost('Hubli', 'Bhubaneshwar', 1620).
pathcost('Bhubaneshwar', 'Hubli', 1620).
pathcost('Hubli', 'Bombay', 614).
pathcost('Bombay', 'Hubli', 614).
pathcost('Hubli', 'Calcutta', 2032).
pathcost('Calcutta', 'Hubli', 2032).
pathcost('Hubli', 'Chandigarh', 2101).
pathcost('Chandigarh', 'Hubli', 2101).
pathcost('Hubli', 'Cochin', 774).
pathcost('Cochin', 'Hubli', 774).
pathcost('Hubli', 'Delhi', 1854).
pathcost('Delhi', 'Hubli', 1854).
pathcost('Hubli', 'Hyderabad', 486).
pathcost('Hyderabad', 'Hubli', 486).
pathcost('Hubli', 'Indore', 1060).
pathcost('Indore', 'Hubli', 1060).
pathcost('Hubli', 'Jaipur', 1060).
pathcost('Jaipur', 'Hubli', 1060).
pathcost('Hubli', 'Kanpur', 1772).
pathcost('Kanpur', 'Hubli', 1772).
pathcost('Hubli', 'Lucknow', 1851).
pathcost('Lucknow', 'Hubli', 1851).
pathcost('Hubli', 'Madras', 683).
pathcost('Madras', 'Hubli', 683).
pathcost('Hubli', 'Nagpur', 995).
pathcost('Nagpur', 'Hubli', 995).
pathcost('Hubli', 'Nasik', 646).
pathcost('Nasik', 'Hubli', 646).
pathcost('Hubli', 'Panjim', 190).
pathcost('Panjim', 'Hubli', 190).
pathcost('Hubli', 'Patna', 1998).
pathcost('Patna', 'Hubli', 1998).
pathcost('Hubli', 'Pondicherry', 653).
pathcost('Pondicherry', 'Hubli', 653).
pathcost('Hubli', 'Pune', 437).
pathcost('Pune', 'Hubli', 437).
pathcost('Hyderabad', 'Ahmedabad', 1436).
pathcost('Ahmedabad', 'Hyderabad', 1436).
pathcost('Hyderabad', 'Bangalore', 563).
pathcost('Bangalore', 'Hyderabad', 563).
pathcost('Hyderabad', 'Bhubaneshwar', 1044).
pathcost('Bhubaneshwar', 'Hyderabad', 1044).
pathcost('Hyderabad', 'Bombay', 729).
pathcost('Bombay', 'Hyderabad', 729).
pathcost('Hyderabad', 'Calcutta', 1467).
pathcost('Calcutta', 'Hyderabad', 1467).
pathcost('Hyderabad', 'Chandigarh', 1693).
pathcost('Chandigarh', 'Hyderabad', 1693).
pathcost('Hyderabad', 'Cochin', 1090).
pathcost('Cochin', 'Hyderabad', 1090).
pathcost('Hyderabad', 'Delhi', 1447).
pathcost('Delhi', 'Hyderabad', 1447).
pathcost('Hyderabad', 'Indore', 999).
pathcost('Indore', 'Hyderabad', 999).
pathcost('Hyderabad', 'Jaipur', 1404).
pathcost('Jaipur', 'Hyderabad', 1404).
pathcost('Hyderabad', 'Kanpur', 1253).
pathcost('Kanpur', 'Hyderabad', 1253).
pathcost('Hyderabad', 'Lucknow', 1332).
pathcost('Lucknow', 'Hyderabad', 1332).
pathcost('Hyderabad', 'Madras', 699).
pathcost('Madras', 'Hyderabad', 699).
pathcost('Hyderabad', 'Nagpur', 476).
pathcost('Nagpur', 'Hyderabad', 476).
pathcost('Hyderabad', 'Nasik', 754).
pathcost('Nasik', 'Hyderabad', 754).
pathcost('Hyderabad', 'Panjim', 765).
pathcost('Panjim', 'Hyderabad', 765).
pathcost('Hyderabad', 'Patna', 1469).
pathcost('Patna', 'Hyderabad', 1469).
pathcost('Hyderabad', 'Pondicherry', 865).
pathcost('Pondicherry', 'Hyderabad', 865).
pathcost('Hyderabad', 'Pune', 545).
pathcost('Pune', 'Hyderabad', 545).
pathcost('Imphal', 'Ahmedabad', 3240).
pathcost('Ahmedabad', 'Imphal', 3240).
pathcost('Imphal', 'Bangalore', 3677).
pathcost('Bangalore', 'Imphal', 3677).
pathcost('Imphal', 'Bhubaneshwar', 2139).
pathcost('Bhubaneshwar', 'Imphal', 2139).
pathcost('Imphal', 'Bombay', 3446).
pathcost('Bombay', 'Imphal', 3446).
pathcost('Imphal', 'Calcutta', 1717).
pathcost('Calcutta', 'Imphal', 1717).
pathcost('Imphal', 'Chandigarh', 2851).
pathcost('Chandigarh', 'Imphal', 2851).
pathcost('Imphal', 'Cochin', 4156).
pathcost('Cochin', 'Imphal', 4156).
pathcost('Imphal', 'Delhi', 2561).
pathcost('Delhi', 'Imphal', 2561).
pathcost('Imphal', 'Hyderabad', 3283).
pathcost('Hyderabad', 'Imphal', 3283).
pathcost('Imphal', 'Indore', 2744).
pathcost('Indore', 'Imphal', 2744).
pathcost('Imphal', 'Jaipur', 2654).
pathcost('Jaipur', 'Imphal', 2654).
pathcost('Imphal', 'Kanpur', 2134).
pathcost('Kanpur', 'Imphal', 2134).
pathcost('Imphal', 'Lucknow', 2105).
pathcost('Lucknow', 'Imphal', 2105).
pathcost('Imphal', 'Madras', 3326).
pathcost('Madras', 'Imphal', 3326).
pathcost('Imphal', 'Nagpur', 2549).
pathcost('Nagpur', 'Imphal', 2549).
pathcost('Imphal', 'Nasik', 3218).
pathcost('Nasik', 'Imphal', 3218).
pathcost('Imphal', 'Panjim', 3360).
pathcost('Panjim', 'Imphal', 3360).
pathcost('Imphal', 'Patna', 1534).
pathcost('Patna', 'Imphal', 1534).
pathcost('Imphal', 'Pondicherry', 3614).
pathcost('Pondicherry', 'Imphal', 3614).
pathcost('Imphal', 'Pune', 3295).
pathcost('Pune', 'Imphal', 3295).
pathcost('Indore', 'Ahmedabad', 442).
pathcost('Ahmedabad', 'Indore', 442).
pathcost('Indore', 'Bangalore', 1601).
pathcost('Bangalore', 'Indore', 1601).
pathcost('Indore', 'Bhubaneshwar', 1355).
pathcost('Bhubaneshwar', 'Indore', 1355).
pathcost('Indore', 'Bombay', 589).
pathcost('Bombay', 'Indore', 589).
pathcost('Indore', 'Calcutta', 1620).
pathcost('Calcutta', 'Indore', 1620).
pathcost('Indore', 'Chandigarh', 1052).
pathcost('Chandigarh', 'Indore', 1052).
pathcost('Indore', 'Cochin', 1804).
pathcost('Cochin', 'Indore', 1804).
pathcost('Indore', 'Delhi', 806).
pathcost('Delhi', 'Indore', 806).
pathcost('Indore', 'Hyderabad', 999).
pathcost('Hyderabad', 'Indore', 999).
pathcost('Indore', 'Jaipur', 405).
pathcost('Jaipur', 'Indore', 405).
pathcost('Indore', 'Kanpur', 689).
pathcost('Kanpur', 'Indore', 689).
pathcost('Indore', 'Lucknow', 768).
pathcost('Lucknow', 'Indore', 768).
pathcost('Indore', 'Madras', 1795).
pathcost('Madras', 'Indore', 1795).
pathcost('Indore', 'Nagpur', 445).
pathcost('Nagpur', 'Indore', 445).
pathcost('Indore', 'Nasik', 414).
pathcost('Nasik', 'Indore', 414).
pathcost('Indore', 'Panjim', 1115).
pathcost('Panjim', 'Indore', 1115).
pathcost('Indore', 'Patna', 1205).
pathcost('Patna', 'Indore', 1205).
pathcost('Indore', 'Pondicherry', 1963).
pathcost('Pondicherry', 'Indore', 1963).
pathcost('Indore', 'Pune', 623).
pathcost('Pune', 'Indore', 623).
pathcost('Jabalpur', 'Ahmedabad', 901).
pathcost('Ahmedabad', 'Jabalpur', 901).
pathcost('Jabalpur', 'Bangalore', 1335).
pathcost('Bangalore', 'Jabalpur', 1335).
pathcost('Jabalpur', 'Bhubaneshwar', 1087).
pathcost('Bhubaneshwar', 'Jabalpur', 1087).
pathcost('Jabalpur', 'Bombay', 1143).
pathcost('Bombay', 'Jabalpur', 1143).
pathcost('Jabalpur', 'Calcutta', 1167).
pathcost('Calcutta', 'Jabalpur', 1167).
pathcost('Jabalpur', 'Chandigarh', 1046).
pathcost('Chandigarh', 'Jabalpur', 1046).
pathcost('Jabalpur', 'Cochin', 1885).
pathcost('Cochin', 'Jabalpur', 1885).
pathcost('Jabalpur', 'Delhi', 800).
pathcost('Delhi', 'Jabalpur', 800).
pathcost('Jabalpur', 'Hyderabad', 733).
pathcost('Hyderabad', 'Jabalpur', 733).
pathcost('Jabalpur', 'Indore', 859).
pathcost('Indore', 'Jabalpur', 859).
pathcost('Jabalpur', 'Jaipur', 845).
pathcost('Jaipur', 'Jabalpur', 845).
pathcost('Jabalpur', 'Kanpur', 543).
pathcost('Kanpur', 'Jabalpur', 543).
pathcost('Jabalpur', 'Lucknow', 584).
pathcost('Lucknow', 'Jabalpur', 584).
pathcost('Jabalpur', 'Madras', 1529).
pathcost('Madras', 'Jabalpur', 1529).
pathcost('Jabalpur', 'Nagpur', 257).
pathcost('Nagpur', 'Jabalpur', 257).
pathcost('Jabalpur', 'Nasik', 943).
pathcost('Nasik', 'Jabalpur', 943).
pathcost('Jabalpur', 'Panjim', 1088).
pathcost('Panjim', 'Jabalpur', 1088).
pathcost('Jabalpur', 'Patna', 736).
pathcost('Patna', 'Jabalpur', 736).
pathcost('Jabalpur', 'Pondicherry', 1697).
pathcost('Pondicherry', 'Jabalpur', 1697).
pathcost('Jabalpur', 'Pune', 1003).
pathcost('Pune', 'Jabalpur', 1003).
pathcost('Jaipur', 'Ahmedabad', 648).
pathcost('Ahmedabad', 'Jaipur', 648).
pathcost('Jaipur', 'Bangalore', 2005).
pathcost('Bangalore', 'Jaipur', 2005).
pathcost('Jaipur', 'Bhubaneshwar', 1758).
pathcost('Bhubaneshwar', 'Jaipur', 1758).
pathcost('Jaipur', 'Bombay', 1148).
pathcost('Bombay', 'Jaipur', 1148).
pathcost('Jaipur', 'Calcutta', 1530).
pathcost('Calcutta', 'Jaipur', 1530).
pathcost('Jaipur', 'Chandigarh', 507).
pathcost('Chandigarh', 'Jaipur', 507).
pathcost('Jaipur', 'Cochin', 2745).
pathcost('Cochin', 'Jaipur', 2745).
pathcost('Jaipur', 'Delhi', 263).
pathcost('Delhi', 'Jaipur', 263).
pathcost('Jaipur', 'Hyderabad', 1404).
pathcost('Hyderabad', 'Jaipur', 1404).
pathcost('Jaipur', 'Indore', 405).
pathcost('Indore', 'Jaipur', 405).
pathcost('Jaipur', 'Kanpur', 517).
pathcost('Kanpur', 'Jaipur', 517).
pathcost('Jaipur', 'Lucknow', 598).
pathcost('Lucknow', 'Jaipur', 598).
pathcost('Jaipur', 'Madras', 2200).
pathcost('Madras', 'Jaipur', 2200).
pathcost('Jaipur', 'Nagpur', 928).
pathcost('Nagpur', 'Jaipur', 928).
pathcost('Jaipur', 'Nasik', 1248).
pathcost('Nasik', 'Jaipur', 1248).
pathcost('Jaipur', 'Panjim', 2496).
pathcost('Panjim', 'Jaipur', 2496).
pathcost('Jaipur', 'Patna', 1115).
pathcost('Patna', 'Jaipur', 1115).
pathcost('Jaipur', 'Pondicherry', 2368).
pathcost('Pondicherry', 'Jaipur', 2368).
pathcost('Jaipur', 'Pune', 1371).
pathcost('Pune', 'Jaipur', 1371).
pathcost('Jamshedpur', 'Ahmedabad', 1225).
pathcost('Ahmedabad', 'Jamshedpur', 1225).
pathcost('Jamshedpur', 'Bangalore', 1690).
pathcost('Bangalore', 'Jamshedpur', 1690).
pathcost('Jamshedpur', 'Bhubaneshwar', 422).
pathcost('Bhubaneshwar', 'Jamshedpur', 422).
pathcost('Jamshedpur', 'Bombay', 1916).
pathcost('Bombay', 'Jamshedpur', 1916).
pathcost('Jamshedpur', 'Calcutta', 268).
pathcost('Calcutta', 'Jamshedpur', 268).
pathcost('Jamshedpur', 'Chandigarh', 1602).
pathcost('Chandigarh', 'Jamshedpur', 1602).
pathcost('Jamshedpur', 'Cochin', 2710).
pathcost('Cochin', 'Jamshedpur', 2710).
pathcost('Jamshedpur', 'Delhi', 1356).
pathcost('Delhi', 'Jamshedpur', 1356).
pathcost('Jamshedpur', 'Hyderabad', 1578).
pathcost('Hyderabad', 'Jamshedpur', 1578).
pathcost('Jamshedpur', 'Indore', 1477).
pathcost('Indore', 'Jamshedpur', 1477).
pathcost('Jamshedpur', 'Jaipur', 1387).
pathcost('Jaipur', 'Jamshedpur', 1387).
pathcost('Jamshedpur', 'Kanpur', 867).
pathcost('Kanpur', 'Jamshedpur', 867).
pathcost('Jamshedpur', 'Lucknow', 1121).
pathcost('Lucknow', 'Jamshedpur', 1121).
pathcost('Jamshedpur', 'Madras', 1629).
pathcost('Madras', 'Jamshedpur', 1629).
pathcost('Jamshedpur', 'Nagpur', 1102).
pathcost('Nagpur', 'Jamshedpur', 1102).
pathcost('Jamshedpur', 'Nasik', 1788).
pathcost('Nasik', 'Jamshedpur', 1788).
pathcost('Jamshedpur', 'Panjim', 2229).
pathcost('Panjim', 'Jamshedpur', 2229).
pathcost('Jamshedpur', 'Patna', 473).
pathcost('Patna', 'Jamshedpur', 473).
pathcost('Jamshedpur', 'Pondicherry', 1797).
pathcost('Pondicherry', 'Jamshedpur', 1797).
pathcost('Jamshedpur', 'Pune', 1997).
pathcost('Pune', 'Jamshedpur', 1997).
pathcost('Jullundur', 'Ahmedabad', 1285).
pathcost('Ahmedabad', 'Jullundur', 1285).
pathcost('Jullundur', 'Bangalore', 2416).
pathcost('Bangalore', 'Jullundur', 2416).
pathcost('Jullundur', 'Bhubaneshwar', 2413).
pathcost('Bhubaneshwar', 'Jullundur', 2413).
pathcost('Jullundur', 'Bombay', 1778).
pathcost('Bombay', 'Jullundur', 1778).
pathcost('Jullundur', 'Calcutta', 1869).
pathcost('Calcutta', 'Jullundur', 1869).
pathcost('Jullundur', 'Chandigarh', 154).
pathcost('Chandigarh', 'Jullundur', 154).
pathcost('Jullundur', 'Cochin', 3082).
pathcost('Cochin', 'Jullundur', 3082).
pathcost('Jullundur', 'Delhi', 375).
pathcost('Delhi', 'Jullundur', 375).
pathcost('Jullundur', 'Hyderabad', 1821).
pathcost('Hyderabad', 'Jullundur', 1821).
pathcost('Jullundur', 'Indore', 1171).
pathcost('Indore', 'Jullundur', 1171).
pathcost('Jullundur', 'Jaipur', 891).
pathcost('Jaipur', 'Jullundur', 891).
pathcost('Jullundur', 'Kanpur', 855).
pathcost('Kanpur', 'Jullundur', 855).
pathcost('Jullundur', 'Lucknow', 868).
pathcost('Lucknow', 'Jullundur', 868).
pathcost('Jullundur', 'Madras', 2617).
pathcost('Madras', 'Jullundur', 2617).
pathcost('Jullundur', 'Nagpur', 1354).
pathcost('Nagpur', 'Jullundur', 1354).
pathcost('Jullundur', 'Nasik', 1591).
pathcost('Nasik', 'Jullundur', 1591).
pathcost('Jullundur', 'Panjim', 2146).
pathcost('Panjim', 'Jullundur', 2146).
pathcost('Jullundur', 'Patna', 1460).
pathcost('Patna', 'Jullundur', 1460).
pathcost('Jullundur', 'Pondicherry', 2785).
pathcost('Pondicherry', 'Jullundur', 2785).
pathcost('Jullundur', 'Pune', 1791).
pathcost('Pune', 'Jullundur', 1791).
pathcost('Kanpur', 'Ahmedabad', 1168).
pathcost('Ahmedabad', 'Kanpur', 1168).
pathcost('Kanpur', 'Bangalore', 1855).
pathcost('Bangalore', 'Kanpur', 1855).
pathcost('Kanpur', 'Bhubaneshwar', 1283).
pathcost('Bhubaneshwar', 'Kanpur', 1283).
pathcost('Kanpur', 'Bombay', 1278).
pathcost('Bombay', 'Kanpur', 1278).
pathcost('Kanpur', 'Calcutta', 1010).
pathcost('Calcutta', 'Kanpur', 1010).
pathcost('Kanpur', 'Chandigarh', 661).
pathcost('Chandigarh', 'Kanpur', 661).
pathcost('Kanpur', 'Cochin', 2385).
pathcost('Cochin', 'Kanpur', 2385).
pathcost('Kanpur', 'Delhi', 481).
pathcost('Delhi', 'Kanpur', 481).
pathcost('Kanpur', 'Hyderabad', 1253).
pathcost('Hyderabad', 'Kanpur', 1253).
pathcost('Kanpur', 'Indore', 689).
pathcost('Indore', 'Kanpur', 689).
pathcost('Kanpur', 'Jaipur', 517).
pathcost('Jaipur', 'Kanpur', 517).
pathcost('Kanpur', 'Lucknow', 79).
pathcost('Lucknow', 'Kanpur', 79).
pathcost('Kanpur', 'Madras', 2049).
pathcost('Madras', 'Kanpur', 2049).
pathcost('Kanpur', 'Nagpur', 777).
pathcost('Nagpur', 'Kanpur', 777).
pathcost('Kanpur', 'Nasik', 1103).
pathcost('Nasik', 'Kanpur', 1103).
pathcost('Kanpur', 'Panjim', 1813).
pathcost('Panjim', 'Kanpur', 1813).
pathcost('Kanpur', 'Patna', 596).
pathcost('Patna', 'Kanpur', 596).
pathcost('Kanpur', 'Pondicherry', 2217).
pathcost('Pondicherry', 'Kanpur', 2217).
pathcost('Kanpur', 'Pune', 1312).
pathcost('Pune', 'Kanpur', 1312).
pathcost('Kolhapur', 'Ahmedabad', 911).
pathcost('Ahmedabad', 'Kolhapur', 911).
pathcost('Kolhapur', 'Bangalore', 484).
pathcost('Bangalore', 'Kolhapur', 484).
pathcost('Kolhapur', 'Bhubaneshwar', 1622).
pathcost('Bhubaneshwar', 'Kolhapur', 1622).
pathcost('Kolhapur', 'Bombay', 426).
pathcost('Bombay', 'Kolhapur', 426).
pathcost('Kolhapur', 'Calcutta', 2045).
pathcost('Calcutta', 'Kolhapur', 2045).
pathcost('Kolhapur', 'Chandigarh', 1910).
pathcost('Chandigarh', 'Kolhapur', 1910).
pathcost('Kolhapur', 'Cochin', 934).
pathcost('Cochin', 'Kolhapur', 934).
pathcost('Kolhapur', 'Delhi', 1664).
pathcost('Delhi', 'Kolhapur', 1664).
pathcost('Kolhapur', 'Hyderabad', 578).
pathcost('Hyderabad', 'Kolhapur', 578).
pathcost('Kolhapur', 'Indore', 870).
pathcost('Indore', 'Kolhapur', 870).
pathcost('Kolhapur', 'Jaipur', 1518).
pathcost('Jaipur', 'Kolhapur', 1518).
pathcost('Kolhapur', 'Kanpur', 1779).
pathcost('Kanpur', 'Kolhapur', 1779).
pathcost('Kolhapur', 'Lucknow', 1858).
pathcost('Lucknow', 'Kolhapur', 1858).
pathcost('Kolhapur', 'Madras', 910).
pathcost('Madras', 'Kolhapur', 910).
pathcost('Kolhapur', 'Nagpur', 1050).
pathcost('Nagpur', 'Kolhapur', 1050).
pathcost('Kolhapur', 'Nasik', 456).
pathcost('Nasik', 'Kolhapur', 456).
pathcost('Kolhapur', 'Panjim', 254).
pathcost('Panjim', 'Kolhapur', 254).
pathcost('Kolhapur', 'Patna', 2047).
pathcost('Patna', 'Kolhapur', 2047).
pathcost('Kolhapur', 'Pondicherry', 907).
pathcost('Pondicherry', 'Kolhapur', 907).
pathcost('Kolhapur', 'Pune', 247).
pathcost('Pune', 'Kolhapur', 247).
pathcost('Lucknow', 'Ahmedabad', 1247).
pathcost('Ahmedabad', 'Lucknow', 1247).
pathcost('Lucknow', 'Bangalore', 1934).
pathcost('Bangalore', 'Lucknow', 1934).
pathcost('Lucknow', 'Bhubaneshwar', 1254).
pathcost('Bhubaneshwar', 'Lucknow', 1254).
pathcost('Lucknow', 'Bombay', 1366).
pathcost('Bombay', 'Lucknow', 1366).
pathcost('Lucknow', 'Calcutta', 1089).
pathcost('Calcutta', 'Lucknow', 1089).
pathcost('Lucknow', 'Chandigarh', 740).
pathcost('Chandigarh', 'Lucknow', 740).
pathcost('Lucknow', 'Cochin', 2572).
pathcost('Cochin', 'Lucknow', 2572).
pathcost('Lucknow', 'Delhi', 499).
pathcost('Delhi', 'Lucknow', 499).
pathcost('Lucknow', 'Hyderabad', 1332).
pathcost('Hyderabad', 'Lucknow', 1332).
pathcost('Lucknow', 'Indore', 768).
pathcost('Indore', 'Lucknow', 768).
pathcost('Lucknow', 'Jaipur', 598).
pathcost('Jaipur', 'Lucknow', 598).
pathcost('Lucknow', 'Kanpur', 79).
pathcost('Kanpur', 'Lucknow', 79).
pathcost('Lucknow', 'Madras', 2128).
pathcost('Madras', 'Lucknow', 2128).
pathcost('Lucknow', 'Nagpur', 856).
pathcost('Nagpur', 'Lucknow', 856).
pathcost('Lucknow', 'Nasik', 1182).
pathcost('Nasik', 'Lucknow', 1182).
pathcost('Lucknow', 'Panjim', 1883).
pathcost('Panjim', 'Lucknow', 1883).
pathcost('Lucknow', 'Patna', 566).
pathcost('Patna', 'Lucknow', 566).
pathcost('Lucknow', 'Pondicherry', 2296).
pathcost('Pondicherry', 'Lucknow', 2296).
pathcost('Lucknow', 'Pune', 1391).
pathcost('Pune', 'Lucknow', 1391).
pathcost('Ludhiana', 'Ahmedabad', 1220).
pathcost('Ahmedabad', 'Ludhiana', 1220).
pathcost('Ludhiana', 'Bangalore', 2358).
pathcost('Bangalore', 'Ludhiana', 2358).
pathcost('Ludhiana', 'Bhubaneshwar', 2088).
pathcost('Bhubaneshwar', 'Ludhiana', 2088).
pathcost('Ludhiana', 'Bombay', 1770).
pathcost('Bombay', 'Ludhiana', 1770).
pathcost('Ludhiana', 'Calcutta', 1783).
pathcost('Calcutta', 'Ludhiana', 1783).
pathcost('Ludhiana', 'Chandigarh', 105).
pathcost('Chandigarh', 'Ludhiana', 105).
pathcost('Ludhiana', 'Cochin', 3027).
pathcost('Cochin', 'Ludhiana', 3027).
pathcost('Ludhiana', 'Delhi', 310).
pathcost('Delhi', 'Ludhiana', 310).
pathcost('Ludhiana', 'Hyderabad', 1756).
pathcost('Hyderabad', 'Ludhiana', 1756).
pathcost('Ludhiana', 'Indore', 1115).
pathcost('Indore', 'Ludhiana', 1115).
pathcost('Ludhiana', 'Jaipur', 570).
pathcost('Jaipur', 'Ludhiana', 570).
pathcost('Ludhiana', 'Kanpur', 790).
pathcost('Kanpur', 'Ludhiana', 790).
pathcost('Ludhiana', 'Lucknow', 803).
pathcost('Lucknow', 'Ludhiana', 803).
pathcost('Ludhiana', 'Madras', 2552).
pathcost('Madras', 'Ludhiana', 2552).
pathcost('Ludhiana', 'Nagpur', 1280).
pathcost('Nagpur', 'Ludhiana', 1280).
pathcost('Ludhiana', 'Nasik', 1528).
pathcost('Nasik', 'Ludhiana', 1528).
pathcost('Ludhiana', 'Panjim', 2091).
pathcost('Panjim', 'Ludhiana', 2091).
pathcost('Ludhiana', 'Patna', 1395).
pathcost('Patna', 'Ludhiana', 1395).
pathcost('Ludhiana', 'Pondicherry', 2720).
pathcost('Pondicherry', 'Ludhiana', 2720).
pathcost('Ludhiana', 'Pune', 1726).
pathcost('Pune', 'Ludhiana', 1726).
pathcost('Madras', 'Ahmedabad', 1821).
pathcost('Ahmedabad', 'Madras', 1821).
pathcost('Madras', 'Bangalore', 331).
pathcost('Bangalore', 'Madras', 331).
pathcost('Madras', 'Bhubaneshwar', 1207).
pathcost('Bhubaneshwar', 'Madras', 1207).
pathcost('Madras', 'Bombay', 1344).
pathcost('Bombay', 'Madras', 1344).
pathcost('Madras', 'Calcutta', 1630).
pathcost('Calcutta', 'Madras', 1630).
pathcost('Madras', 'Chandigarh', 2489).
pathcost('Chandigarh', 'Madras', 2489).
pathcost('Madras', 'Cochin', 687).
pathcost('Cochin', 'Madras', 687).
pathcost('Madras', 'Delhi', 2243).
pathcost('Delhi', 'Madras', 2243).
pathcost('Madras', 'Hyderabad', 699).
pathcost('Hyderabad', 'Madras', 699).
pathcost('Madras', 'Indore', 1795).
pathcost('Indore', 'Madras', 1795).
pathcost('Madras', 'Jaipur', 2200).
pathcost('Jaipur', 'Madras', 2200).
pathcost('Madras', 'Kanpur', 2049).
pathcost('Kanpur', 'Madras', 2049).
pathcost('Madras', 'Lucknow', 2128).
pathcost('Lucknow', 'Madras', 2128).
pathcost('Madras', 'Nagpur', 1272).
pathcost('Nagpur', 'Madras', 1272).
pathcost('Madras', 'Nasik', 1366).
pathcost('Nasik', 'Madras', 1366).
pathcost('Madras', 'Panjim', 909).
pathcost('Panjim', 'Madras', 909).
pathcost('Madras', 'Patna', 2096).
pathcost('Patna', 'Madras', 2096).
pathcost('Madras', 'Pondicherry', 168).
pathcost('Pondicherry', 'Madras', 168).
pathcost('Madras', 'Pune', 1157).
pathcost('Pune', 'Madras', 1157).
pathcost('Madurai', 'Ahmedabad', 1922).
pathcost('Ahmedabad', 'Madurai', 1922).
pathcost('Madurai', 'Bangalore', 432).
pathcost('Bangalore', 'Madurai', 432).
pathcost('Madurai', 'Bhubaneshwar', 1687).
pathcost('Bhubaneshwar', 'Madurai', 1687).
pathcost('Madurai', 'Bombay', 1458).
pathcost('Bombay', 'Madurai', 1458).
pathcost('Madurai', 'Calcutta', 2110).
pathcost('Calcutta', 'Madurai', 2110).
pathcost('Madurai', 'Chandigarh', 2785).
pathcost('Chandigarh', 'Madurai', 2785).
pathcost('Madurai', 'Cochin', 326).
pathcost('Cochin', 'Madurai', 326).
pathcost('Madurai', 'Delhi', 2539).
pathcost('Delhi', 'Madurai', 2539).
pathcost('Madurai', 'Hyderabad', 995).
pathcost('Hyderabad', 'Madurai', 995).
pathcost('Madurai', 'Indore', 2091).
pathcost('Indore', 'Madurai', 2091).
pathcost('Madurai', 'Jaipur', 2496).
pathcost('Jaipur', 'Madurai', 2496).
pathcost('Madurai', 'Kanpur', 2345).
pathcost('Kanpur', 'Madurai', 2345).
pathcost('Madurai', 'Lucknow', 2424).
pathcost('Lucknow', 'Madurai', 2424).
pathcost('Madurai', 'Madras', 480).
pathcost('Madras', 'Madurai', 480).
pathcost('Madurai', 'Nagpur', 1568).
pathcost('Nagpur', 'Madurai', 1568).
pathcost('Madurai', 'Nasik', 1467).
pathcost('Nasik', 'Madurai', 1467).
pathcost('Madurai', 'Panjim', 872).
pathcost('Panjim', 'Madurai', 872).
pathcost('Madurai', 'Patna', 2561).
pathcost('Patna', 'Madurai', 2561).
pathcost('Madurai', 'Pondicherry', 333).
pathcost('Pondicherry', 'Madurai', 333).
pathcost('Madurai', 'Pune', 1238).
pathcost('Pune', 'Madurai', 1238).
pathcost('Meerut', 'Ahmedabad', 1092).
pathcost('Ahmedabad', 'Meerut', 1092).
pathcost('Meerut', 'Bangalore', 2072).
pathcost('Bangalore', 'Meerut', 2072).
pathcost('Meerut', 'Bhubaneshwar', 1822).
pathcost('Bhubaneshwar', 'Meerut', 1822).
pathcost('Meerut', 'Bombay', 1468).
pathcost('Bombay', 'Meerut', 1468).
pathcost('Meerut', 'Calcutta', 1497).
pathcost('Calcutta', 'Meerut', 1497).
pathcost('Meerut', 'Chandigarh', 381).
pathcost('Chandigarh', 'Meerut', 381).
pathcost('Meerut', 'Cochin', 2741).
pathcost('Cochin', 'Meerut', 2741).
pathcost('Meerut', 'Delhi', 66).
pathcost('Delhi', 'Meerut', 66).
pathcost('Meerut', 'Hyderabad', 1470).
pathcost('Hyderabad', 'Meerut', 1470).
pathcost('Meerut', 'Indore', 815).
pathcost('Indore', 'Meerut', 815).
pathcost('Meerut', 'Jaipur', 327).
pathcost('Jaipur', 'Meerut', 327).
pathcost('Meerut', 'Kanpur', 537).
pathcost('Kanpur', 'Meerut', 537).
pathcost('Meerut', 'Lucknow', 453).
pathcost('Lucknow', 'Meerut', 453).
pathcost('Meerut', 'Madras', 2266).
pathcost('Madras', 'Meerut', 2266).
pathcost('Meerut', 'Nagpur', 994).
pathcost('Nagpur', 'Meerut', 994).
pathcost('Meerut', 'Nasik', 1242).
pathcost('Nasik', 'Meerut', 1242).
pathcost('Meerut', 'Panjim', 1805).
pathcost('Panjim', 'Meerut', 1805).
pathcost('Meerut', 'Patna', 934).
pathcost('Patna', 'Meerut', 934).
pathcost('Meerut', 'Pondicherry', 2434).
pathcost('Pondicherry', 'Meerut', 2434).
pathcost('Meerut', 'Pune', 1440).
pathcost('Pune', 'Meerut', 1440).
pathcost('Nagpur', 'Ahmedabad', 965).
pathcost('Ahmedabad', 'Nagpur', 965).
pathcost('Nagpur', 'Bangalore', 1078).
pathcost('Bangalore', 'Nagpur', 1078).
pathcost('Nagpur', 'Bhubaneshwar', 830).
pathcost('Bhubaneshwar', 'Nagpur', 830).
pathcost('Nagpur', 'Bombay', 849).
pathcost('Bombay', 'Nagpur', 849).
pathcost('Nagpur', 'Calcutta', 1163).
pathcost('Calcutta', 'Nagpur', 1163).
pathcost('Nagpur', 'Chandigarh', 1217).
pathcost('Chandigarh', 'Nagpur', 1217).
pathcost('Nagpur', 'Cochin', 1608).
pathcost('Cochin', 'Nagpur', 1608).
pathcost('Nagpur', 'Delhi', 971).
pathcost('Delhi', 'Nagpur', 971).
pathcost('Nagpur', 'Hyderabad', 476).
pathcost('Hyderabad', 'Nagpur', 476).
pathcost('Nagpur', 'Indore', 445).
pathcost('Indore', 'Nagpur', 445).
pathcost('Nagpur', 'Jaipur', 928).
pathcost('Jaipur', 'Nagpur', 928).
pathcost('Nagpur', 'Kanpur', 777).
pathcost('Kanpur', 'Nagpur', 777).
pathcost('Nagpur', 'Lucknow', 856).
pathcost('Lucknow', 'Nagpur', 856).
pathcost('Nagpur', 'Madras', 1272).
pathcost('Madras', 'Nagpur', 1272).
pathcost('Nagpur', 'Nasik', 700).
pathcost('Nasik', 'Nagpur', 700).
pathcost('Nagpur', 'Panjim', 1247).
pathcost('Panjim', 'Nagpur', 1247).
pathcost('Nagpur', 'Patna', 993).
pathcost('Patna', 'Nagpur', 993).
pathcost('Nagpur', 'Pondicherry', 1440).
pathcost('Pondicherry', 'Nagpur', 1440).
pathcost('Nagpur', 'Pune', 909).
pathcost('Pune', 'Nagpur', 909).
pathcost('Nasik', 'Ahmedabad', 504).
pathcost('Ahmedabad', 'Nasik', 504).
pathcost('Nasik', 'Bangalore', 1036).
pathcost('Bangalore', 'Nasik', 1036).
pathcost('Nasik', 'Bhubaneshwar', 1516).
pathcost('Bhubaneshwar', 'Nasik', 1516).
pathcost('Nasik', 'Bombay', 197).
pathcost('Bombay', 'Nasik', 197).
pathcost('Nasik', 'Calcutta', 1849).
pathcost('Calcutta', 'Nasik', 1849).
pathcost('Nasik', 'Chandigarh', 1466).
pathcost('Chandigarh', 'Nasik', 1466).
pathcost('Nasik', 'Cochin', 1390).
pathcost('Cochin', 'Nasik', 1390).
pathcost('Nasik', 'Delhi', 1220).
pathcost('Delhi', 'Nasik', 1220).
pathcost('Nasik', 'Hyderabad', 754).
pathcost('Hyderabad', 'Nasik', 754).
pathcost('Nasik', 'Indore', 414).
pathcost('Indore', 'Nasik', 414).
pathcost('Nasik', 'Jaipur', 1246).
pathcost('Jaipur', 'Nasik', 1246).
pathcost('Nasik', 'Kanpur', 1103).
pathcost('Kanpur', 'Nasik', 1103).
pathcost('Nasik', 'Lucknow', 1182).
pathcost('Lucknow', 'Nasik', 1182).
pathcost('Nasik', 'Madras', 1366).
pathcost('Madras', 'Nasik', 1366).
pathcost('Nasik', 'Nagpur', 700).
pathcost('Nagpur', 'Nasik', 700).
pathcost('Nasik', 'Panjim', 701).
pathcost('Panjim', 'Nasik', 701).
pathcost('Nasik', 'Patna', 1679).
pathcost('Patna', 'Nasik', 1679).
pathcost('Nasik', 'Pondicherry', 1363).
pathcost('Pondicherry', 'Nasik', 1363).
pathcost('Nasik', 'Pune', 209).
pathcost('Pune', 'Nasik', 209).
pathcost('Panjim', 'Ahmedabad', 1165).
pathcost('Ahmedabad', 'Panjim', 1165).
pathcost('Panjim', 'Bangalore', 440).
pathcost('Bangalore', 'Panjim', 440).
pathcost('Panjim', 'Bhubaneshwar', 1455).
pathcost('Bhubaneshwar', 'Panjim', 1455).
pathcost('Panjim', 'Bombay', 584).
pathcost('Bombay', 'Panjim', 584).
pathcost('Panjim', 'Calcutta', 974).
pathcost('Calcutta', 'Panjim', 974).
pathcost('Panjim', 'Chandigarh', 2028).
pathcost('Chandigarh', 'Panjim', 2028).
pathcost('Panjim', 'Cochin', 798).
pathcost('Cochin', 'Panjim', 798).
pathcost('Panjim', 'Delhi', 1782).
pathcost('Delhi', 'Panjim', 1782).
pathcost('Panjim', 'Hyderabad', 765).
pathcost('Hyderabad', 'Panjim', 765).
pathcost('Panjim', 'Indore', 1115).
pathcost('Indore', 'Panjim', 1115).
pathcost('Panjim', 'Jaipur', 2496).
pathcost('Jaipur', 'Panjim', 2496).
pathcost('Panjim', 'Kanpur', 1813).
pathcost('Kanpur', 'Panjim', 1813).
pathcost('Panjim', 'Lucknow', 1883).
pathcost('Lucknow', 'Panjim', 1883).
pathcost('Panjim', 'Madras', 909).
pathcost('Madras', 'Panjim', 909).
pathcost('Panjim', 'Nagpur', 1247).
pathcost('Nagpur', 'Panjim', 1247).
pathcost('Panjim', 'Nasik', 701).
pathcost('Nasik', 'Panjim', 701).
pathcost('Panjim', 'Patna', 1804).
pathcost('Patna', 'Panjim', 1804).
pathcost('Panjim', 'Pondicherry', 739).
pathcost('Pondicherry', 'Panjim', 739).
pathcost('Panjim', 'Pune', 501).
pathcost('Pune', 'Panjim', 501).
pathcost('Patna', 'Ahmedabad', 1656).
pathcost('Ahmedabad', 'Patna', 1656).
pathcost('Patna', 'Bangalore', 2071).
pathcost('Bangalore', 'Patna', 2071).
pathcost('Patna', 'Bhubaneshwar', 862).
pathcost('Bhubaneshwar', 'Patna', 862).
pathcost('Patna', 'Bombay', 1856).
pathcost('Bombay', 'Patna', 1856).
pathcost('Patna', 'Calcutta', 621).
pathcost('Calcutta', 'Patna', 621).
pathcost('Patna', 'Chandigarh', 1332).
pathcost('Chandigarh', 'Patna', 1332).
pathcost('Patna', 'Cochin', 2601).
pathcost('Cochin', 'Patna', 2601).
pathcost('Patna', 'Delhi', 1086).
pathcost('Delhi', 'Patna', 1086).
pathcost('Patna', 'Hyderabad', 1489).
pathcost('Hyderabad', 'Patna', 1489).
pathcost('Patna', 'Indore', 1205).
pathcost('Indore', 'Patna', 1205).
pathcost('Patna', 'Jaipur', 1115).
pathcost('Jaipur', 'Patna', 1115).
pathcost('Patna', 'Kanpur', 595).
pathcost('Kanpur', 'Patna', 595).
pathcost('Patna', 'Lucknow', 566).
pathcost('Lucknow', 'Patna', 566).
pathcost('Patna', 'Madras', 2096).
pathcost('Madras', 'Patna', 2096).
pathcost('Patna', 'Nagpur', 993).
pathcost('Nagpur', 'Patna', 993).
pathcost('Patna', 'Nasik', 1679).
pathcost('Nasik', 'Patna', 1679).
pathcost('Patna', 'Panjim', 1804).
pathcost('Panjim', 'Patna', 1804).
pathcost('Patna', 'Pondicherry', 2264).
pathcost('Pondicherry', 'Patna', 2264).
pathcost('Patna', 'Pune', 1738).
pathcost('Pune', 'Patna', 1738).
pathcost('Pondicherry', 'Ahmedabad', 1818).
pathcost('Ahmedabad', 'Pondicherry', 1818).
pathcost('Pondicherry', 'Bangalore', 328).
pathcost('Bangalore', 'Pondicherry', 328).
pathcost('Pondicherry', 'Bhubaneshwar', 1375).
pathcost('Bhubaneshwar', 'Pondicherry', 1375).
pathcost('Pondicherry', 'Bombay', 1452).
pathcost('Bombay', 'Pondicherry', 1452).
pathcost('Pondicherry', 'Calcutta', 1798).
pathcost('Calcutta', 'Pondicherry', 1798).
pathcost('Pondicherry', 'Chandigarh', 2657).
pathcost('Chandigarh', 'Pondicherry', 2657).
pathcost('Pondicherry', 'Cochin', 530).
pathcost('Cochin', 'Pondicherry', 530).
pathcost('Pondicherry', 'Delhi', 2411).
pathcost('Delhi', 'Pondicherry', 2411).
pathcost('Pondicherry', 'Hyderabad', 867).
pathcost('Hyderabad', 'Pondicherry', 867).
pathcost('Pondicherry', 'Indore', 1963).
pathcost('Indore', 'Pondicherry', 1963).
pathcost('Pondicherry', 'Jaipur', 2368).
pathcost('Jaipur', 'Pondicherry', 2368).
pathcost('Pondicherry', 'Kanpur', 2217).
pathcost('Kanpur', 'Pondicherry', 2217).
pathcost('Pondicherry', 'Lucknow', 2296).
pathcost('Lucknow', 'Pondicherry', 2296).
pathcost('Pondicherry', 'Madras', 168).
pathcost('Madras', 'Pondicherry', 168).
pathcost('Pondicherry', 'Nagpur', 1440).
pathcost('Nagpur', 'Pondicherry', 1440).
pathcost('Pondicherry', 'Nasik', 1363).
pathcost('Nasik', 'Pondicherry', 1363).
pathcost('Pondicherry', 'Panjim', 739).
pathcost('Panjim', 'Pondicherry', 739).
pathcost('Pondicherry', 'Patna', 2264).
pathcost('Patna', 'Pondicherry', 2264).
pathcost('Pondicherry', 'Pune', 1154).
pathcost('Pune', 'Pondicherry', 1154).
pathcost('Pune', 'Ahmedabad', 664).
pathcost('Ahmedabad', 'Pune', 664).
pathcost('Pune', 'Bangalore', 826).
pathcost('Bangalore', 'Pune', 826).
pathcost('Pune', 'Bhubaneshwar', 1587).
pathcost('Bhubaneshwar', 'Pune', 1587).
pathcost('Pune', 'Bombay', 184).
pathcost('Bombay', 'Pune', 184).
pathcost('Pune', 'Calcutta', 2058).
pathcost('Calcutta', 'Pune', 2058).
pathcost('Pune', 'Chandigarh', 1663).
pathcost('Chandigarh', 'Pune', 1663).
pathcost('Pune', 'Cochin', 1181).
pathcost('Cochin', 'Pune', 1181).
pathcost('Pune', 'Delhi', 1417).
pathcost('Delhi', 'Pune', 1417).
pathcost('Pune', 'Hyderabad', 545).
pathcost('Hyderabad', 'Pune', 545).
pathcost('Pune', 'Indore', 623).
pathcost('Indore', 'Pune', 623).
pathcost('Pune', 'Jaipur', 1371).
pathcost('Jaipur', 'Pune', 1371).
pathcost('Pune', 'Kanpur', 1312).
pathcost('Kanpur', 'Pune', 1312).
pathcost('Pune', 'Lucknow', 1391).
pathcost('Lucknow', 'Pune', 1391).
pathcost('Pune', 'Madras', 1157).
pathcost('Madras', 'Pune', 1157).
pathcost('Pune', 'Nagpur', 909).
pathcost('Nagpur', 'Pune', 909).
pathcost('Pune', 'Nasik', 209).
pathcost('Nasik', 'Pune', 209).
pathcost('Pune', 'Panjim', 501).
pathcost('Panjim', 'Pune', 501).
pathcost('Pune', 'Patna', 1738).
pathcost('Patna', 'Pune', 1738).
pathcost('Pune', 'Pondicherry', 1154).
pathcost('Pondicherry', 'Pune', 1154).
pathcost('Ranchi', 'Ahmedabad', 1781).
pathcost('Ahmedabad', 'Ranchi', 1781).
pathcost('Ranchi', 'Bangalore', 2098).
pathcost('Bangalore', 'Ranchi', 2098).
pathcost('Ranchi', 'Bhubaneshwar', 560).
pathcost('Bhubaneshwar', 'Ranchi', 560).
pathcost('Ranchi', 'Bombay', 1816).
pathcost('Bombay', 'Ranchi', 1816).
pathcost('Ranchi', 'Calcutta', 414).
pathcost('Calcutta', 'Ranchi', 414).
pathcost('Ranchi', 'Chandigarh', 1480).
pathcost('Chandigarh', 'Ranchi', 1480).
pathcost('Ranchi', 'Cochin', 2455).
pathcost('Cochin', 'Ranchi', 2455).
pathcost('Ranchi', 'Delhi', 1214).
pathcost('Delhi', 'Ranchi', 1214).
pathcost('Ranchi', 'Hyderabad', 1434).
pathcost('Hyderabad', 'Ranchi', 1434).
pathcost('Ranchi', 'Indore', 1333).
pathcost('Indore', 'Ranchi', 1333).
pathcost('Ranchi', 'Jaipur', 1243).
pathcost('Jaipur', 'Ranchi', 1243).
pathcost('Ranchi', 'Kanpur', 723).
pathcost('Kanpur', 'Ranchi', 723).
pathcost('Ranchi', 'Lucknow', 912).
pathcost('Lucknow', 'Ranchi', 912).
pathcost('Ranchi', 'Madras', 1767).
pathcost('Madras', 'Ranchi', 1767).
pathcost('Ranchi', 'Nagpur', 958).
pathcost('Nagpur', 'Ranchi', 958).
pathcost('Ranchi', 'Nasik', 1615).
pathcost('Nasik', 'Ranchi', 1615).
pathcost('Ranchi', 'Panjim', 1630).
pathcost('Panjim', 'Ranchi', 1630).
pathcost('Ranchi', 'Patna', 302).
pathcost('Patna', 'Ranchi', 302).
pathcost('Ranchi', 'Pondicherry', 1935).
pathcost('Pondicherry', 'Ranchi', 1935).
pathcost('Ranchi', 'Pune', 1675).
pathcost('Pune', 'Ranchi', 1675).
pathcost('Shillong', 'Ahmedabad', 2839).
pathcost('Ahmedabad', 'Shillong', 2839).
pathcost('Shillong', 'Bangalore', 3242).
pathcost('Bangalore', 'Shillong', 3242).
pathcost('Shillong', 'Bhubaneshwar', 1640).
pathcost('Bhubaneshwar', 'Shillong', 1640).
pathcost('Shillong', 'Bombay', 3011).
pathcost('Bombay', 'Shillong', 3011).
pathcost('Shillong', 'Calcutta', 1281).
pathcost('Calcutta', 'Shillong', 1281).
pathcost('Shillong', 'Chandigarh', 2416).
pathcost('Chandigarh', 'Shillong', 2416).
pathcost('Shillong', 'Cochin', 3599).
pathcost('Cochin', 'Shillong', 3599).
pathcost('Shillong', 'Delhi', 2126).
pathcost('Delhi', 'Shillong', 2126).
pathcost('Shillong', 'Hyderabad', 1309).
pathcost('Hyderabad', 'Shillong', 1309).
pathcost('Shillong', 'Indore', 2309).
pathcost('Indore', 'Shillong', 2309).
pathcost('Shillong', 'Jaipur', 2229).
pathcost('Jaipur', 'Shillong', 2229).
pathcost('Shillong', 'Kanpur', 1699).
pathcost('Kanpur', 'Shillong', 1699).
pathcost('Shillong', 'Lucknow', 1670).
pathcost('Lucknow', 'Shillong', 1670).
pathcost('Shillong', 'Madras', 2911).
pathcost('Madras', 'Shillong', 2911).
pathcost('Shillong', 'Nagpur', 2114).
pathcost('Nagpur', 'Shillong', 2114).
pathcost('Shillong', 'Nasik', 2800).
pathcost('Nasik', 'Shillong', 2800).
pathcost('Shillong', 'Panjim', 2925).
pathcost('Panjim', 'Shillong', 2925).
pathcost('Shillong', 'Patna', 1019).
pathcost('Patna', 'Shillong', 1019).
pathcost('Shillong', 'Pondicherry', 3079).
pathcost('Pondicherry', 'Shillong', 3079).
pathcost('Shillong', 'Pune', 2860).
pathcost('Pune', 'Shillong', 2860).
pathcost('Shimla', 'Ahmedabad', 1256).
pathcost('Ahmedabad', 'Shimla', 1256).
pathcost('Shimla', 'Bangalore', 2395).
pathcost('Bangalore', 'Shimla', 2395).
pathcost('Shimla', 'Bhubaneshwar', 2127).
pathcost('Bhubaneshwar', 'Shimla', 2127).
pathcost('Shimla', 'Bombay', 1753).
pathcost('Bombay', 'Shimla', 1753).
pathcost('Shimla', 'Calcutta', 1839).
pathcost('Calcutta', 'Shimla', 1839).
pathcost('Shimla', 'Chandigarh', 99).
pathcost('Chandigarh', 'Shimla', 99).
pathcost('Shimla', 'Cochin', 3056).
pathcost('Cochin', 'Shimla', 3056).
pathcost('Shimla', 'Delhi', 365).
pathcost('Delhi', 'Shimla', 365).
pathcost('Shimla', 'Hyderabad', 1812).
pathcost('Hyderabad', 'Shimla', 1812).
pathcost('Shimla', 'Indore', 1171).
pathcost('Indore', 'Shimla', 1171).
pathcost('Shimla', 'Jaipur', 636).
pathcost('Jaipur', 'Shimla', 636).
pathcost('Shimla', 'Kanpur', 846).
pathcost('Kanpur', 'Shimla', 846).
pathcost('Shimla', 'Lucknow', 659).
pathcost('Lucknow', 'Shimla', 659).
pathcost('Shimla', 'Madras', 2588).
pathcost('Madras', 'Shimla', 2588).
pathcost('Shimla', 'Nagpur', 1336).
pathcost('Nagpur', 'Shimla', 1336).
pathcost('Shimla', 'Nasik', 1567).
pathcost('Nasik', 'Shimla', 1567).
pathcost('Shimla', 'Panjim', 2130).
pathcost('Panjim', 'Shimla', 2130).
pathcost('Shimla', 'Patna', 1434).
pathcost('Patna', 'Shimla', 1434).
pathcost('Shimla', 'Pondicherry', 2759).
pathcost('Pondicherry', 'Shimla', 2759).
pathcost('Shimla', 'Pune', 1782).
pathcost('Pune', 'Shimla', 1782).
pathcost('Surat', 'Ahmedabad', 263).
pathcost('Ahmedabad', 'Surat', 263).
pathcost('Surat', 'Bangalore', 1264).
pathcost('Bangalore', 'Surat', 1264).
pathcost('Surat', 'Bhubaneshwar', 1579).
pathcost('Bhubaneshwar', 'Surat', 1579).
pathcost('Surat', 'Bombay', 301).
pathcost('Bombay', 'Surat', 301).
pathcost('Surat', 'Calcutta', 1912).
pathcost('Calcutta', 'Surat', 1912).
pathcost('Surat', 'Chandigarh', 1325).
pathcost('Chandigarh', 'Surat', 1325).
pathcost('Surat', 'Cochin', 1593).
pathcost('Cochin', 'Surat', 1593).
pathcost('Surat', 'Delhi', 1182).
pathcost('Delhi', 'Surat', 1182).
pathcost('Surat', 'Hyderabad', 983).
pathcost('Hyderabad', 'Surat', 983).
pathcost('Surat', 'Indore', 607).
pathcost('Indore', 'Surat', 607).
pathcost('Surat', 'Jaipur', 932).
pathcost('Jaipur', 'Surat', 932).
pathcost('Surat', 'Kanpur', 1296).
pathcost('Kanpur', 'Surat', 1296).
pathcost('Surat', 'Lucknow', 1375).
pathcost('Lucknow', 'Surat', 1375).
pathcost('Surat', 'Madras', 1695).
pathcost('Madras', 'Surat', 1695).
pathcost('Surat', 'Nagpur', 749).
pathcost('Nagpur', 'Surat', 749).
pathcost('Surat', 'Nasik', 262).
pathcost('Nasik', 'Surat', 262).
pathcost('Surat', 'Panjim', 913).
pathcost('Panjim', 'Surat', 913).
pathcost('Surat', 'Patna', 1742).
pathcost('Patna', 'Surat', 1742).
pathcost('Surat', 'Pondicherry', 1789).
pathcost('Pondicherry', 'Surat', 1789).
pathcost('Surat', 'Pune', 412).
pathcost('Pune', 'Surat', 412).
pathcost('Trivandrum', 'Ahmedabad', 2197).
pathcost('Ahmedabad', 'Trivandrum', 2197).
pathcost('Trivandrum', 'Bangalore', 696).
pathcost('Bangalore', 'Trivandrum', 696).
pathcost('Trivandrum', 'Bhubaneshwar', 1953).
pathcost('Bhubaneshwar', 'Trivandrum', 1953).
pathcost('Trivandrum', 'Bombay', 1376).
pathcost('Bombay', 'Trivandrum', 1376).
pathcost('Trivandrum', 'Calcutta', 2376).
pathcost('Calcutta', 'Trivandrum', 2376).
pathcost('Trivandrum', 'Chandigarh', 3051).
pathcost('Chandigarh', 'Trivandrum', 3051).
pathcost('Trivandrum', 'Cochin', 218).
pathcost('Cochin', 'Trivandrum', 218).
pathcost('Trivandrum', 'Delhi', 1950).
pathcost('Delhi', 'Trivandrum', 1950).
pathcost('Trivandrum', 'Hyderabad', 1261).
pathcost('Hyderabad', 'Trivandrum', 1261).
pathcost('Trivandrum', 'Indore', 2156).
pathcost('Indore', 'Trivandrum', 2156).
pathcost('Trivandrum', 'Jaipur', 2782).
pathcost('Jaipur', 'Trivandrum', 2782).
pathcost('Trivandrum', 'Kanpur', 2611).
pathcost('Kanpur', 'Trivandrum', 2611).
pathcost('Trivandrum', 'Lucknow', 2690).
pathcost('Lucknow', 'Trivandrum', 2690).
pathcost('Trivandrum', 'Madras', 748).
pathcost('Madras', 'Trivandrum', 748).
pathcost('Trivandrum', 'Nagpur', 1834).
pathcost('Nagpur', 'Trivandrum', 1834).
pathcost('Trivandrum', 'Nasik', 1742).
pathcost('Nasik', 'Trivandrum', 1742).
pathcost('Trivandrum', 'Panjim', 792).
pathcost('Panjim', 'Trivandrum', 792).
pathcost('Trivandrum', 'Patna', 2827).
pathcost('Patna', 'Trivandrum', 2827).
pathcost('Trivandrum', 'Pondicherry', 622).
pathcost('Pondicherry', 'Trivandrum', 622).
pathcost('Trivandrum', 'Pune', 1533).
pathcost('Pune', 'Trivandrum', 1533).
pathcost('Varanasi', 'Ahmedabad', 1373).
pathcost('Ahmedabad', 'Varanasi', 1373).
pathcost('Varanasi', 'Bangalore', 1791).
pathcost('Bangalore', 'Varanasi', 1791).
pathcost('Varanasi', 'Bhubaneshwar', 968).
pathcost('Bhubaneshwar', 'Varanasi', 968).
pathcost('Varanasi', 'Bombay', 1597).
pathcost('Bombay', 'Varanasi', 1597).
pathcost('Varanasi', 'Calcutta', 695).
pathcost('Calcutta', 'Varanasi', 695).
pathcost('Varanasi', 'Chandigarh', 1032).
pathcost('Chandigarh', 'Varanasi', 1032).
pathcost('Varanasi', 'Cochin', 2331).
pathcost('Cochin', 'Varanasi', 2331).
pathcost('Varanasi', 'Delhi', 745).
pathcost('Delhi', 'Varanasi', 745).
pathcost('Varanasi', 'Hyderabad', 1189).
pathcost('Hyderabad', 'Varanasi', 1189).
pathcost('Varanasi', 'Indore', 925).
pathcost('Indore', 'Varanasi', 925).
pathcost('Varanasi', 'Jaipur', 835).
pathcost('Jaipur', 'Varanasi', 835).
pathcost('Varanasi', 'Kanpur', 315).
pathcost('Kanpur', 'Varanasi', 315).
pathcost('Varanasi', 'Lucknow', 286).
pathcost('Lucknow', 'Varanasi', 286).
pathcost('Varanasi', 'Madras', 1985).
pathcost('Madras', 'Varanasi', 1985).
pathcost('Varanasi', 'Nagpur', 713).
pathcost('Nagpur', 'Varanasi', 713).
pathcost('Varanasi', 'Nasik', 1399).
pathcost('Nasik', 'Varanasi', 1399).
pathcost('Varanasi', 'Panjim', 1524).
pathcost('Panjim', 'Varanasi', 1524).
pathcost('Varanasi', 'Patna', 280).
pathcost('Patna', 'Varanasi', 280).
pathcost('Varanasi', 'Pondicherry', 2153).
pathcost('Pondicherry', 'Varanasi', 2153).
pathcost('Varanasi', 'Pune', 1459).
pathcost('Pune', 'Varanasi', 1459).
pathcost('Vijayawada', 'Ahmedabad', 1705).
pathcost('Ahmedabad', 'Vijayawada', 1705).
pathcost('Vijayawada', 'Bangalore', 637).
pathcost('Bangalore', 'Vijayawada', 637).
pathcost('Vijayawada', 'Bhubaneshwar', 775).
pathcost('Bhubaneshwar', 'Vijayawada', 775).
pathcost('Vijayawada', 'Bombay', 973).
pathcost('Bombay', 'Vijayawada', 973).
pathcost('Vijayawada', 'Calcutta', 1198).
pathcost('Calcutta', 'Vijayawada', 1198).
pathcost('Vijayawada', 'Chandigarh', 1959).
pathcost('Chandigarh', 'Vijayawada', 1959).
pathcost('Vijayawada', 'Cochin', 1174).
pathcost('Cochin', 'Vijayawada', 1174).
pathcost('Vijayawada', 'Delhi', 1716).
pathcost('Delhi', 'Vijayawada', 1716).
pathcost('Vijayawada', 'Hyderabad', 269).
pathcost('Hyderabad', 'Vijayawada', 269).
pathcost('Vijayawada', 'Indore', 1255).
pathcost('Indore', 'Vijayawada', 1255).
pathcost('Vijayawada', 'Jaipur', 1660).
pathcost('Jaipur', 'Vijayawada', 1660).
pathcost('Vijayawada', 'Kanpur', 1519).
pathcost('Kanpur', 'Vijayawada', 1519).
pathcost('Vijayawada', 'Lucknow', 1598).
pathcost('Lucknow', 'Vijayawada', 1598).
pathcost('Vijayawada', 'Madras', 432).
pathcost('Madras', 'Vijayawada', 432).
pathcost('Vijayawada', 'Nagpur', 742).
pathcost('Nagpur', 'Vijayawada', 742).
pathcost('Vijayawada', 'Nasik', 1428).
pathcost('Nasik', 'Vijayawada', 1428).
pathcost('Vijayawada', 'Panjim', 876).
pathcost('Panjim', 'Vijayawada', 876).
pathcost('Vijayawada', 'Patna', 1664).
pathcost('Patna', 'Vijayawada', 1664).
pathcost('Vijayawada', 'Pondicherry', 598).
pathcost('Pondicherry', 'Vijayawada', 598).
pathcost('Vijayawada', 'Pune', 842).
pathcost('Pune', 'Vijayawada', 842).
pathcost('Vishakapatnam', 'Ahmedabad', 1815).
pathcost('Ahmedabad', 'Vishakapatnam', 1815).
pathcost('Vishakapatnam', 'Bangalore', 1093).
pathcost('Bangalore', 'Vishakapatnam', 1093).
pathcost('Vishakapatnam', 'Bhubaneshwar', 445).
pathcost('Bhubaneshwar', 'Vishakapatnam', 445).
pathcost('Vishakapatnam', 'Bombay', 1754).
pathcost('Bombay', 'Vishakapatnam', 1754).
pathcost('Vishakapatnam', 'Calcutta', 868).
pathcost('Calcutta', 'Vishakapatnam', 868).
pathcost('Vishakapatnam', 'Chandigarh', 2127).
pathcost('Chandigarh', 'Vishakapatnam', 2127).
pathcost('Vishakapatnam', 'Cochin', 1449).
pathcost('Cochin', 'Vishakapatnam', 1449).
pathcost('Vishakapatnam', 'Delhi', 1881).
pathcost('Delhi', 'Vishakapatnam', 1881).
pathcost('Vishakapatnam', 'Hyderabad', 599).
pathcost('Hyderabad', 'Vishakapatnam', 599).
pathcost('Vishakapatnam', 'Indore', 1433).
pathcost('Indore', 'Vishakapatnam', 1433).
pathcost('Vishakapatnam', 'Jaipur', 1838).
pathcost('Jaipur', 'Vishakapatnam', 1838).
pathcost('Vishakapatnam', 'Kanpur', 1687).
pathcost('Kanpur', 'Vishakapatnam', 1687).
pathcost('Vishakapatnam', 'Lucknow', 1765).
pathcost('Lucknow', 'Vishakapatnam', 1765).
pathcost('Vishakapatnam', 'Madras', 762).
pathcost('Madras', 'Vishakapatnam', 762).
pathcost('Vishakapatnam', 'Nagpur', 910).
pathcost('Nagpur', 'Vishakapatnam', 910).
pathcost('Vishakapatnam', 'Nasik', 1596).
pathcost('Nasik', 'Vishakapatnam', 1596).
pathcost('Vishakapatnam', 'Panjim', 1206).
pathcost('Panjim', 'Vishakapatnam', 1206).
pathcost('Vishakapatnam', 'Patna', 1334).
pathcost('Patna', 'Vishakapatnam', 1334).
pathcost('Vishakapatnam', 'Pondicherry', 930).
pathcost('Pondicherry', 'Vishakapatnam', 930).
pathcost('Vishakapatnam', 'Pune', 1658).
pathcost('Pune', 'Vishakapatnam', 1658).

