#MT22001
# -*- coding: utf-8 -*-
"""AIAssignment3_MT22001.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OtIS0dPoQgfL6Ouuub7_rp5DUEMiJEly
"""


from durable.lang import *

def specialization_area():
  print('Enter your area of expertise: ')
  print('1. Cloud Computing')
  print('2. Mobile Computing')
  print('3. Unity and Game Development')
  print('4. Data Analysis and and Wrangling')
  print('5. Maintaing Servers and other Network Infrastructure')
  print('6. Big Data Applications')
  print('7. Ethical Hacking')
  print('8. Database Management')
  interest = input()
  return interest





with ruleset('courses'):

   @when_all((m.course_interest == '1')& (m.grades == '1'))
   def career_sugg(cs):
     interest = specialization_area()
     sub = 'AI'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':sub})

   @when_all((m.course_interest == '1')& (m.grades == '2'))
   def career_sugg(cs):
     interest = specialization_area()
     sub = 'AI'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':sub})
     
   @when_all((m.course_interest == '1')& (m.grades == '3'))
   def career_sugg(cs):
     interest = specialization_area()
     sub = 'AI'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':sub})

   @when_all((m.course_interest == '2')& (m.grades == '1'))
   def career_sugg(cs):
     interest = specialization_area()
     sub = 'ML'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':sub})

   @when_all((m.course_interest == '2')& (m.grades == '2'))
   def career_sugg(cs):
     interest = specialization_area()
     sub = 'ML'
     if(interest == '4'):
       cs.assert_fact({'suggestion':'You can pursue career as an Data Analyst'})
     else:
       cs.assert_fact('domains' , {'selected_interest': interest, 'subject':sub})

   @when_all((m.course_interest == '2')& (m.grades == '3'))
   def career_sugg(cs):
     interest = specialization_area()
     sub = 'ML'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':sub})


   @when_all((m.course_interest == '3')& (m.grades == '1'))
   def career_sugg(cs):
     interest = specialization_area()
     sub = 'CN'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':sub})


   @when_all((m.course_interest == '3')& (m.grades == '2'))
   def career_sugg(cs):
     interest = specialization_area()
     subj = 'CN'
     if(interest == '7'):
       m.assert_fact({ 'suggestion': 'You can pursue career as a Network Security Engineer'})
     else:
       cs.assert_fact('domains' , {'selected_interest': interest, 'subject':subj}) 

   @when_all((m.course_interest == '3')& (m.grades == '3'))
   def career_sugg(cs):
     interest = specialization_area()
     subj = 'CN'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':subj})


   @when_all((m.course_interest == '4')& (m.grades == '1'))
   def career_sugg(cs):
     interest = specialization_area()
     subj = 'DB'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':subj})

   @when_all((m.course_interest == '4')& (m.grades == '2'))
   def career_sugg(cs):
     interest = specialization_area()
     subj = 'DB'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':subj})

   @when_all((m.course_interest == '4')& (m.grades == '3'))
   def career_sugg(cs):
     interest = specialization_area()
     subj = 'DB'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':subj})


   @when_all((m.course_interest == '5')& (m.grades == '1'))
   def career_sugg(cs):
     interest = specialization_area()
     subj = 'JP'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':subj})

   @when_all((m.course_interest == '5')& (m.grades == '2'))
   def career_sugg(cs):
     interest = specialization_area()
     subj = 'JP'
     if(interest == '2'):
       cs.assert_fact({'suggestion':'You can pursue career as an Android App Developer'})
     else:
       cs.assert_fact('domains' , {'selected_interest': interest, 'subject':subj})

   @when_all((m.course_interest == '5')& (m.grades == '3'))
   def career_sugg(cs):
     interest = specialization_area()
     subj = 'JP'
     cs.assert_fact('domains' , {'selected_interest': interest, 'subject':subj})


   @when_all(+m.suggestion)
   def suggestion(cs):
     print('Course Suggestion: {0}'.format(cs.m.suggestion))

#======================================================================

with ruleset('domains'):

    @when_all((m.selected_interest == '1')& (m.subject == 'DB'))
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': 'Cloud Engineer Role'})

    @when_all((m.selected_interest == '1')& (m.subject == 'CN'))
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': 'Cloud Engineer Role'})

    @when_all((m.selected_interest == '2')& (m.subject == 'JP')) 
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': 'Android App Developer Role'})

    @when_all((m.selected_interest == '3')& (m.subject == 'JP'))
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': 'Unity Game developer Role'})

    @when_all((m.selected_interest == '4')& (m.subject == 'ML'))
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': 'Data Scientist Role'})

    @when_all((m.selected_interest == '5')& (m.subject == 'CN'))
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': 'Site Reliability Engineer Role'})
  
    @when_all((m.selected_interest == '6')& (m.subject == 'AI'))
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': 'Big Data Engineer Role'})
  
    @when_all((m.selected_interest == '7')& (m.subject == 'CN'))
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': ' Ethical Hacker Role'})

    @when_all((m.selected_interest == '8')& (m.subject == 'ML'))
    def interest_gd(m): 
        m.assert_fact({ 'Suggestion': 'Data Analyst Role'})


    @when_all(+m.suggestion)
    def output(cs):
        print('Specialization Suggestion is as follows: {0}'.format(cs.m.suggestion))

print('Welcome to Career Advisory System of IIIT-Delhi:')

print('This system advises you to choose appropriate career which you can opt for depending on courses done by you , your grades and your domains')

print('Select any one of following courses that you have done and enter its grades')

print('1. Artificial Intelligence')

print('2. Machine Learning')

print('3. Computer Network')

print('4. Database Management')

print('5. Java Programming')

course_int = input()
print('Enter the grade/cgpa obtained in the course selected')
print('1) 8-10    2) 6-7    3) Less than 6')
grade = input()

assert_fact('courses', { 'course_interest': course_int, 'grades': grade})

